// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { InputText } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Input / Text",
  component: InputText,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Disabled",
      "Hover",
      "Focus",
      "Filled",
      "Error"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Show optional": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show hint": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show error message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show Payment method icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Hint": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Error message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show tooltip": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show link": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Input / Text", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=72-21377" },
    docs: { description: { component: "**Figma:** `Input / Text` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=72-21377)\n\n**Tier:** Molecule\n\n**Use:** Single-line text input; 'Show icon' makes it the Select / Dropdown trigger.\n\n**Built from:** `Icon`\n\n**Known Figma gaps (see gaps.md):** no Success state; Show Payment method icon / Show link belong to other variants\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof InputText>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Disabled", "Hover", "Focus", "Filled", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <InputText {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
