// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { MenuItem } from '../../components/FormElements';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Form Elements/Menu / Item",
  component: MenuItem,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Selected",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show leading icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Leading icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Menu / Item", page: "➜ Input Fields and Dropdown", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2024" },
    docs: { description: { component: "**Figma:** `Menu / Item` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2024)\n\n**Tier:** Atom\n\n**Use:** One option row for Menu / Select.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof MenuItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Selected: Story = { name: "Selected", args: { "State": "Selected" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Selected", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <MenuItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
