// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { OTPCell } from '../../components/FormElements';

const meta = {
  title: "Form Elements/OTP / Cell",
  component: OTPCell,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Empty",
      "Hover",
      "Focus",
      "Filled",
      "Error",
      "Success",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"State": "Empty"},
  parameters: {
    figma: { name: "OTP / Cell", page: "➜ Input Fields and Dropdown", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=68-20624" },
    docs: { description: { component: "**Figma:** `OTP / Cell` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=68-20624)\n\n**Tier:** Atom\n\n**Use:** One OTP digit cell (60x60). Building block of OTP / Field and Stepper; never alone.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof OTPCell>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Empty: Story = { name: "Empty", args: { "State": "Empty" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Empty", "Hover", "Focus", "Filled", "Error", "Success", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <OTPCell {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
