// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { SelectDropdown } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Select / Dropdown",
  component: SelectDropdown,
  tags: ['autodocs', 'tier-organism'],
  argTypes: {
  "Open": {
    "control": "inline-radio",
    "options": [
      "False",
      "True"
    ],
    "description": "Figma variant property `Open`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Open": "False"},
  parameters: {
    figma: { name: "Select / Dropdown", page: "➜ Input Fields and Dropdown", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2169" },
    docs: { description: { component: "**Figma:** `Select / Dropdown` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2169)\n\n**Tier:** Organism\n\n**Use:** Select field: Input / Text (chevron on) + Menu.\n\n**Built from:** `Input / Text`, `Menu`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof SelectDropdown>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const False: Story = { name: "False", args: { "Open": "False" } };
export const True: Story = { name: "True", args: { "Open": "True" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["False", "True"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Open={x}</div>
          <SelectDropdown {...args} {...{ "Open": x } as any} />
        </div>
      ))}
    </div>
  ),
};
