// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { UploadField } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Upload Field",
  component: UploadField,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Disabled",
      "Hover",
      "Uploaded",
      "Error"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Show Label": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Hint Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show (Optional)": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show Help Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Upload Field", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-28810" },
    docs: { description: { component: "**Figma:** `Upload Field` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-28810)\n\n**Tier:** Molecule\n\n**Use:** Single-file picker with dashed drop zone; Uploaded shows file name + delete.\n\n**Built from:** `Icon/Upload`, `Icon/File`, `Icon/Delete`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof UploadField>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Uploaded: Story = { name: "Uploaded", args: { "State": "Uploaded" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Disabled", "Hover", "Uploaded", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <UploadField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
