// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Button } from '../../components/Navigation';

const meta = {
  title: "Navigation/Button",
  component: Button,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "select",
    "options": [
      "Filled",
      "Outline",
      "Pill",
      "Link",
      "Danger"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Size": {
    "control": "select",
    "options": [
      "base",
      "lg",
      "sm",
      "xl",
      "xs"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Icon": {
    "control": "inline-radio",
    "options": [
      "None",
      "Left",
      "Right",
      "Only"
    ],
    "description": "Figma variant property `Icon`",
    "table": {
      "category": "Figma variants"
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Focus",
      "Hover",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Type": "Filled", "Size": "base", "Icon": "None", "State": "Default"},
  parameters: {
    figma: { name: "Button", page: "➜  Buttons & links", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=103-859" },
    docs: { description: { component: "**Figma:** `Button` on page `➜  Buttons & links` (Navigation). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=103-859)\n\n**Tier:** Atom\n\n**Use:** Filled = primary (one per section), Outline = secondary, Pill = rounded CTA, Link = tertiary, Danger = destructive.\n\n**Built from:** `Icon`\n\n**Known Figma gaps (see gaps.md):** no Pressed/Loading state; no TEXT property for the label or INSTANCE_SWAP for icons\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Filled: Story = { name: "Filled", args: { "Type": "Filled" } };
export const Outline: Story = { name: "Outline", args: { "Type": "Outline" } };
export const Pill: Story = { name: "Pill", args: { "Type": "Pill" } };
export const Link: Story = { name: "Link", args: { "Type": "Link" } };
export const Danger: Story = { name: "Danger", args: { "Type": "Danger" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Filled", "Outline", "Pill", "Link", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Focus", "Hover", "Disabled"].map((y) => <Button key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
