// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Avatar } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Avatar",
  component: Avatar,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Icon",
      "Photo",
      "Initials"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Size": {
    "control": "inline-radio",
    "options": [
      "Large",
      "Medium",
      "Small",
      "XSmall"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Type": "Icon", "Size": "Large"},
  parameters: {
    figma: { name: "Avatar", page: "➜ Avatars & upload image", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26830" },
    docs: { description: { component: "**Figma:** `Avatar` on page `➜ Avatars & upload image` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26830)\n\n**Tier:** Atom\n\n**Use:** Photo when available, Initials otherwise, Icon for anonymous.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Icon: Story = { name: "Icon", args: { "Type": "Icon" } };
export const Photo: Story = { name: "Photo", args: { "Type": "Photo" } };
export const Initials: Story = { name: "Initials", args: { "Type": "Initials" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Icon", "Photo", "Initials"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Large", "Medium", "Small", "XSmall"].map((y) => <Avatar key={y} {...args} {...{ "Type": x, "Size": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
