// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { ConfirmationPopup } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Confirmation Popup",
  component: ConfirmationPopup,
  tags: ['autodocs', 'tier-organism'],
  argTypes: {
  "Status": {
    "control": "inline-radio",
    "options": [
      "Success",
      "Info",
      "Warning",
      "Danger"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Body": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show close": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"Status": "Success"},
  parameters: {
    figma: { name: "Confirmation Popup", page: "➜ Popups", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=222-3717" },
    docs: { description: { component: "**Figma:** `Confirmation Popup` on page `➜ Popups` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=222-3717)\n\n**Tier:** Organism\n\n**Use:** Confirmation dialog: status icon, title, body, Cancel (Outline) + confirm (Filled / Danger).\n\n**Built from:** `Icon`, `Button x2`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof ConfirmationPopup>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Info: Story = { name: "Info", args: { "Status": "Info" } };
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Danger: Story = { name: "Danger", args: { "Status": "Danger" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Success", "Info", "Warning", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <ConfirmationPopup {...args} {...{ "Status": x } as any} />
        </div>
      ))}
    </div>
  ),
};
