// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Toast } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Toast",
  component: Toast,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "Status": {
    "control": "inline-radio",
    "options": [
      "Info",
      "Success",
      "Warning",
      "Error"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show close": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"Status": "Info"},
  parameters: {
    figma: { name: "Toast", page: "➜ Banners & Badges", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2012-543" },
    docs: { description: { component: "**Figma:** `Toast` on page `➜ Banners & Badges` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2012-543)\n\n**Tier:** Molecule\n\n**Use:** Short transient feedback after an action (auto-dismiss 4-6 s).\n\n**Built from:** `Icon`, `Button (Link, Icon=Only)`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Toast>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Info: Story = { name: "Info", args: { "Status": "Info" } };
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Error: Story = { name: "Error", args: { "Status": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Info", "Success", "Warning", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <Toast {...args} {...{ "Status": x } as any} />
        </div>
      ))}
    </div>
  ),
};
