// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Breadcrumb } from '../../components/Navigation';

const meta = {
  title: "Navigation/Breadcrumb",
  component: Breadcrumb,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Breadcrumb", page: "➜ Paganation & Tabs", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2013-594" },
    docs: { description: { component: "**Figma:** `Breadcrumb` on page `➜ Paganation & Tabs` (Navigation). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2013-594)\n\n**Tier:** Molecule\n\n**Use:** Breadcrumb trail.\n\n**Built from:** `Breadcrumb / Item`, `Icon/Chevron Right`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Breadcrumb>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
