// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { BreadcrumbItem } from '../../components/Navigation';

const meta = {
  title: "Navigation/Breadcrumb / Item",
  component: BreadcrumbItem,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Current"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Breadcrumb / Item", page: "➜ Paganation & Tabs", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2013-593" },
    docs: { description: { component: "**Figma:** `Breadcrumb / Item` on page `➜ Paganation & Tabs` (Navigation). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2013-593)\n\n**Tier:** Atom\n\n**Use:** One breadcrumb link.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof BreadcrumbItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Current: Story = { name: "Current", args: { "State": "Current" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Current"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <BreadcrumbItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
