// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Pagination, PaginationItem } from '../../components/Navigation';

const meta = {
  title: "Navigation/Pagination / Item",
  component: PaginationItem,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Number",
      "Ellipsis",
      "Prev",
      "Next"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants"
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Active",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Type": "Number", "State": "Default"},
  parameters: {
    figma: { name: "Pagination / Item", page: "➜ Paganation & Tabs", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=245-24" },
    docs: { description: { component: "**Figma:** `Pagination / Item` on page `➜ Paganation & Tabs` (Navigation). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=245-24)\n\n**Tier:** Atom\n\n**Use:** Pagination cell; Active = current page.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof PaginationItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Number: Story = { name: "Number", args: { "Type": "Number" } };
export const Ellipsis: Story = { name: "Ellipsis", args: { "Type": "Ellipsis" } };
export const Prev: Story = { name: "Prev", args: { "Type": "Prev" } };
export const Next: Story = { name: "Next", args: { "Type": "Next" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Number", "Ellipsis", "Prev", "Next"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Hover", "Active", "Disabled"].map((y) => <PaginationItem key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <Pagination /> };
