// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TabUnderline, Tabs } from '../../components/Navigation';

const meta = {
  title: "Navigation/Tabs / Item — Underline",
  component: TabUnderline,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Style": {
    "control": "inline-radio",
    "options": [
      "Underline"
    ],
    "description": "Figma variant property `Style`",
    "table": {
      "category": "Figma variants"
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Active",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Style": "Underline", "State": "Default"},
  parameters: {
    figma: { name: "Tabs / Item — Underline", page: "➜ Paganation & Tabs", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=245-54" },
    docs: { description: { component: "**Figma:** `Tabs / Item — Underline` on page `➜ Paganation & Tabs` (Navigation). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=245-54)\n\n**Tier:** Atom\n\n**Use:** Switch sibling sections of a page.\n\n**Known Figma gaps (see gaps.md):** no Label text property\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof TabUnderline>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Active: Story = { name: "Active", args: { "State": "Active" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Active", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <TabUnderline {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <Tabs Style="Underline" /> };
