// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Checkbox } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Checkbox",
  component: Checkbox,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Unchecked",
      "Indeterminate",
      "Disabled",
      "Checked",
      "Disabled Checked",
      "Hover",
      "Focus",
      "Checked Hover",
      "Checked Focus"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show text": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Unchecked"},
  parameters: {
    figma: { name: "Checkbox", page: "➜ Checkbox", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2003-636" },
    docs: { description: { component: "**Figma:** `Checkbox` on page `➜ Checkbox` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2003-636)\n\n**Tier:** Atom\n\n**Use:** Multi-select, consent, 'select all' (Indeterminate).\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Unchecked: Story = { name: "Unchecked", args: { "State": "Unchecked" } };
export const Indeterminate: Story = { name: "Indeterminate", args: { "State": "Indeterminate" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Checked: Story = { name: "Checked", args: { "State": "Checked" } };
export const DisabledChecked: Story = { name: "Disabled Checked", args: { "State": "Disabled Checked" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const CheckedHover: Story = { name: "Checked Hover", args: { "State": "Checked Hover" } };
export const CheckedFocus: Story = { name: "Checked Focus", args: { "State": "Checked Focus" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Unchecked", "Indeterminate", "Disabled", "Checked", "Disabled Checked", "Hover", "Focus", "Checked Hover", "Checked Focus"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Checkbox {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
