// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Menu } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Menu",
  component: Menu,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Menu", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2025" },
    docs: { description: { component: "**Figma:** `Menu` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2007-2025)\n\n**Tier:** Molecule\n\n**Use:** List of Menu / Item for dropdowns.\n\n**Built from:** `Menu / Item`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Menu>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
