// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { OTPField } from '../../components/FormElements';

const meta = {
  title: "Form Elements/OTP / Field",
  component: OTPField,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Empty",
      "Filled",
      "Disabled",
      "Success",
      "Error"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Show hint": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show Label": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show success message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Show error message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Hint": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label2": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Hint2": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Empty"},
  parameters: {
    figma: { name: "OTP / Field", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=69-20901" },
    docs: { description: { component: "**Figma:** `OTP / Field` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=69-20901)\n\n**Tier:** Molecule\n\n**Use:** 6-digit verification code with label, hint, success and error messages.\n\n**Built from:** `OTP / Cell`, `Icon/Alert Circle`\n\n**Known Figma gaps (see gaps.md):** generic property names Label2 / Hint2\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof OTPField>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Empty: Story = { name: "Empty", args: { "State": "Empty" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Empty", "Filled", "Disabled", "Success", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <OTPField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
