// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Radio } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Radio",
  component: Radio,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Unchecked",
      "Checked",
      "Checked Disabled",
      "Disabled",
      "Hover",
      "Focus",
      "Checked Hover",
      "Checked Focus"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "Unchecked"},
  parameters: {
    figma: { name: "Radio", page: "➜ Radio Buttons", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-28711" },
    docs: { description: { component: "**Figma:** `Radio` on page `➜ Radio Buttons` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-28711)\n\n**Tier:** Atom\n\n**Use:** One choice among 2-5 visible options.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Unchecked: Story = { name: "Unchecked", args: { "State": "Unchecked" } };
export const Checked: Story = { name: "Checked", args: { "State": "Checked" } };
export const CheckedDisabled: Story = { name: "Checked Disabled", args: { "State": "Checked Disabled" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const CheckedHover: Story = { name: "Checked Hover", args: { "State": "Checked Hover" } };
export const CheckedFocus: Story = { name: "Checked Focus", args: { "State": "Checked Focus" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Unchecked", "Checked", "Checked Disabled", "Disabled", "Hover", "Focus", "Checked Hover", "Checked Focus"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Radio {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
