// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Search } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Search",
  component: Search,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Filled",
      "Focus"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Search", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-30243" },
    docs: { description: { component: "**Figma:** `Search` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=80-30243)\n\n**Tier:** Molecule\n\n**Use:** Search bar with magnifier and clear (x) when Filled; filters lists, tables.\n\n**Built from:** `Icon/Search`, `Icon/Close`\n\n**Known Figma gaps (see gaps.md):** no text property for the placeholder\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Search>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Filled", "Focus"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Search {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
