// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Stepper } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Stepper",
  component: Stepper,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Minimum",
      "Default"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Stepper", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-27016" },
    docs: { description: { component: "**Figma:** `Stepper` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-27016)\n\n**Tier:** Molecule\n\n**Use:** Quantity stepper; Decrease is disabled at Minimum.\n\n**Built from:** `Button (Link, sm, Icon=Only)`, `OTP / Cell`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Stepper>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Minimum: Story = { name: "Minimum", args: { "State": "Minimum" } };
export const Default: Story = { name: "Default", args: { "State": "Default" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Minimum", "Default"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Stepper {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
