// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Toggle } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Toggle",
  component: Toggle,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "On",
      "On Disabled",
      "Off",
      "Off Disabled",
      "On Hover",
      "On Focus",
      "Off Hover",
      "Off Focus"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Show text": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Label2": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"State": "On"},
  parameters: {
    figma: { name: "Toggle", page: "➜ Toggles", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2003-826" },
    docs: { description: { component: "**Figma:** `Toggle` on page `➜ Toggles` (Form Elements). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=2003-826)\n\n**Tier:** Atom\n\n**Use:** Settings that apply immediately.\n\n**Known Figma gaps (see gaps.md):** generic property Label2\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Toggle>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const On: Story = { name: "On", args: { "State": "On" } };
export const OnDisabled: Story = { name: "On Disabled", args: { "State": "On Disabled" } };
export const Off: Story = { name: "Off", args: { "State": "Off" } };
export const OffDisabled: Story = { name: "Off Disabled", args: { "State": "Off Disabled" } };
export const OnHover: Story = { name: "On Hover", args: { "State": "On Hover" } };
export const OnFocus: Story = { name: "On Focus", args: { "State": "On Focus" } };
export const OffHover: Story = { name: "Off Hover", args: { "State": "Off Hover" } };
export const OffFocus: Story = { name: "Off Focus", args: { "State": "Off Focus" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["On", "On Disabled", "Off", "Off Disabled", "On Hover", "On Focus", "Off Hover", "Off Focus"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Toggle {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
