// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { AvatarUpload } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Avatar Upload",
  component: AvatarUpload,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Uploaded",
      "Error"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"State": "Default"},
  parameters: {
    figma: { name: "Avatar Upload", page: "➜ Avatars & upload image", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26917" },
    docs: { description: { component: "**Figma:** `Avatar Upload` on page `➜ Avatars & upload image` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26917)\n\n**Tier:** Molecule\n\n**Use:** Profile photo picker: 100px avatar + edit button.\n\n**Built from:** `Avatar`, `Button (Icon=Only, Icon/Edit)`\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof AvatarUpload>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Uploaded: Story = { name: "Uploaded", args: { "State": "Uploaded" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Uploaded", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <AvatarUpload {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
