// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Badge } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Badge",
  component: Badge,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Status": {
    "control": "inline-radio",
    "options": [
      "Warning",
      "Error",
      "Success",
      "Info"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants"
    }
  }
},
  args: {"Status": "Warning"},
  parameters: {
    figma: { name: "Badge", page: "➜ Banners & Badges", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=77-27864" },
    docs: { description: { component: "**Figma:** `Badge` on page `➜ Banners & Badges` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=77-27864)\n\n**Tier:** Atom\n\n**Use:** Inline status in tables, cards and lists.\n\n**Built from:** `Icon/Info`\n\n**Known Figma gaps (see gaps.md):** no Label text property\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Error: Story = { name: "Error", args: { "Status": "Error" } };
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Info: Story = { name: "Info", args: { "Status": "Info" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Warning", "Error", "Success", "Info"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <Badge {...args} {...{ "Status": x } as any} />
        </div>
      ))}
    </div>
  ),
};
