// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Tooltip } from '../../components/DataDisplay';

const meta = {
  title: "Data display/Tooltip",
  component: Tooltip,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Arrow": {
    "control": "inline-radio",
    "options": [
      "Down",
      "Left",
      "Right",
      "Up"
    ],
    "description": "Figma variant property `Arrow`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Size": {
    "control": "inline-radio",
    "options": [
      "Small",
      "Large"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants"
    }
  },
  "Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  },
  "Text (large)": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties"
    }
  }
},
  args: {"Arrow": "Down", "Size": "Small"},
  parameters: {
    figma: { name: "Tooltip", page: "➜ Tooltips", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26731" },
    docs: { description: { component: "**Figma:** `Tooltip` on page `➜ Tooltips` (Data display). [Open in Figma](https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System?node-id=75-26731)\n\n**Tier:** Atom\n\n**Use:** Small for 1-3 words, Large for 1-2 sentences.\n\nControls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar." } },
  },
} satisfies Meta<typeof Tooltip>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Down: Story = { name: "Down", args: { "Arrow": "Down" } };
export const Left: Story = { name: "Left", args: { "Arrow": "Left" } };
export const Right: Story = { name: "Right", args: { "Arrow": "Right" } };
export const Up: Story = { name: "Up", args: { "Arrow": "Up" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Small", "Large"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Size={x}</div>
          <div className="sb-row">{["Down", "Left", "Right", "Up"].map((y) => <Tooltip key={y} {...args} {...{ "Size": x, "Arrow": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
