// Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand.
export const tokens = {
 "meta": {
  "platform": "Web",
  "figma_file": "Trianglz - Web Design System",
  "figma_url": "https://www.figma.com/design/7qsOqckanKwGDbkljD3rb9/Trianglz---Web-Design-System",
  "source": {
   "method": "figma-console figma_export_tokens (Desktop Bridge, read-only)",
   "file": "Trianglz/data/source/figma-variables.dtcg.json",
   "needs_resync": false
  },
  "generated_at": "2026-09-30",
  "generated_by": "tools/build_tokens.py",
  "naming": "Keys are \"<Collection>::<variable name>\" exactly as in Figma. Find variables by this name, never by id.",
  "recolor": "See rules.json > recolor and tools/recolor.py"
 },
 "collections": {
  "Primitives": {
   "modes": [
    "Value"
   ],
   "default": "Value",
   "attribute": "data-primitives",
   "role": "primitive"
  },
  "Radius": {
   "modes": [
    "Default"
   ],
   "default": "Default",
   "attribute": "data-radius",
   "role": "radius"
  },
  "Semantic": {
   "modes": [
    "Dark",
    "Light"
   ],
   "default": "Light",
   "attribute": "data-semantic",
   "role": "semantic"
  },
  "Spacing": {
   "modes": [
    "Desktop",
    "iPad",
    "Mobile"
   ],
   "default": "Desktop",
   "attribute": "data-spacing",
   "role": "spacing"
  },
  "Typography": {
   "modes": [
    "Desktop",
    "iPad",
    "Mobile"
   ],
   "default": "Desktop",
   "attribute": "data-typography",
   "role": "typography"
  }
 },
 "tokens": [
  {
   "figma": "Primitives::alpha/black-50",
   "collection": "Primitives",
   "name": "alpha/black-50",
   "type": "color",
   "css": "--alpha-black-50",
   "values": {
    "Value": "#02081080"
   },
   "resolved": {
    "Value": "#02081080"
   },
   "description": ""
  },
  {
   "figma": "Primitives::alpha/black-70",
   "collection": "Primitives",
   "name": "alpha/black-70",
   "type": "color",
   "css": "--alpha-black-70",
   "values": {
    "Value": "#000000B2"
   },
   "resolved": {
    "Value": "#000000B2"
   },
   "description": ""
  },
  {
   "figma": "Primitives::black and white/black",
   "collection": "Primitives",
   "name": "black and white/black",
   "type": "color",
   "css": "--black-and-white-black",
   "values": {
    "Value": "#000000"
   },
   "resolved": {
    "Value": "#000000"
   },
   "description": ""
  },
  {
   "figma": "Primitives::black and white/white",
   "collection": "Primitives",
   "name": "black and white/white",
   "type": "color",
   "css": "--black-and-white-white",
   "values": {
    "Value": "#FFFFFF"
   },
   "resolved": {
    "Value": "#FFFFFF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/0",
   "collection": "Primitives",
   "name": "blue/0",
   "type": "color",
   "css": "--blue-0",
   "values": {
    "Value": "#EFF9FF"
   },
   "resolved": {
    "Value": "#EFF9FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/50",
   "collection": "Primitives",
   "name": "blue/50",
   "type": "color",
   "css": "--blue-50",
   "values": {
    "Value": "#EFF6FF"
   },
   "resolved": {
    "Value": "#EFF6FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/100",
   "collection": "Primitives",
   "name": "blue/100",
   "type": "color",
   "css": "--blue-100",
   "values": {
    "Value": "#DBEAFE"
   },
   "resolved": {
    "Value": "#DBEAFE"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/200",
   "collection": "Primitives",
   "name": "blue/200",
   "type": "color",
   "css": "--blue-200",
   "values": {
    "Value": "#BFDBFE"
   },
   "resolved": {
    "Value": "#BFDBFE"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/300",
   "collection": "Primitives",
   "name": "blue/300",
   "type": "color",
   "css": "--blue-300",
   "values": {
    "Value": "#93C5FD"
   },
   "resolved": {
    "Value": "#93C5FD"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/400",
   "collection": "Primitives",
   "name": "blue/400",
   "type": "color",
   "css": "--blue-400",
   "values": {
    "Value": "#60A5FA"
   },
   "resolved": {
    "Value": "#60A5FA"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/500",
   "collection": "Primitives",
   "name": "blue/500",
   "type": "color",
   "css": "--blue-500",
   "values": {
    "Value": "#3B82F6"
   },
   "resolved": {
    "Value": "#3B82F6"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/600",
   "collection": "Primitives",
   "name": "blue/600",
   "type": "color",
   "css": "--blue-600",
   "values": {
    "Value": "#2563EB"
   },
   "resolved": {
    "Value": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/700",
   "collection": "Primitives",
   "name": "blue/700",
   "type": "color",
   "css": "--blue-700",
   "values": {
    "Value": "#1D4ED8"
   },
   "resolved": {
    "Value": "#1D4ED8"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/800",
   "collection": "Primitives",
   "name": "blue/800",
   "type": "color",
   "css": "--blue-800",
   "values": {
    "Value": "#1E40AF"
   },
   "resolved": {
    "Value": "#1E40AF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/900",
   "collection": "Primitives",
   "name": "blue/900",
   "type": "color",
   "css": "--blue-900",
   "values": {
    "Value": "#1E3A8A"
   },
   "resolved": {
    "Value": "#1E3A8A"
   },
   "description": ""
  },
  {
   "figma": "Primitives::blue/950",
   "collection": "Primitives",
   "name": "blue/950",
   "type": "color",
   "css": "--blue-950",
   "values": {
    "Value": "#172554"
   },
   "resolved": {
    "Value": "#172554"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/0",
   "collection": "Primitives",
   "name": "gray/0",
   "type": "color",
   "css": "--gray-0",
   "values": {
    "Value": "#FAFAFA"
   },
   "resolved": {
    "Value": "#FAFAFA"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/50",
   "collection": "Primitives",
   "name": "gray/50",
   "type": "color",
   "css": "--gray-50",
   "values": {
    "Value": "#F9FAFB"
   },
   "resolved": {
    "Value": "#F9FAFB"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/100",
   "collection": "Primitives",
   "name": "gray/100",
   "type": "color",
   "css": "--gray-100",
   "values": {
    "Value": "#F3F4F6"
   },
   "resolved": {
    "Value": "#F3F4F6"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/200",
   "collection": "Primitives",
   "name": "gray/200",
   "type": "color",
   "css": "--gray-200",
   "values": {
    "Value": "#E5E7EB"
   },
   "resolved": {
    "Value": "#E5E7EB"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/300",
   "collection": "Primitives",
   "name": "gray/300",
   "type": "color",
   "css": "--gray-300",
   "values": {
    "Value": "#D1D5DB"
   },
   "resolved": {
    "Value": "#D1D5DB"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/400",
   "collection": "Primitives",
   "name": "gray/400",
   "type": "color",
   "css": "--gray-400",
   "values": {
    "Value": "#9CA3AF"
   },
   "resolved": {
    "Value": "#9CA3AF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/500",
   "collection": "Primitives",
   "name": "gray/500",
   "type": "color",
   "css": "--gray-500",
   "values": {
    "Value": "#6B7280"
   },
   "resolved": {
    "Value": "#6B7280"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/600",
   "collection": "Primitives",
   "name": "gray/600",
   "type": "color",
   "css": "--gray-600",
   "values": {
    "Value": "#4B5563"
   },
   "resolved": {
    "Value": "#4B5563"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/700",
   "collection": "Primitives",
   "name": "gray/700",
   "type": "color",
   "css": "--gray-700",
   "values": {
    "Value": "#374151"
   },
   "resolved": {
    "Value": "#374151"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/800",
   "collection": "Primitives",
   "name": "gray/800",
   "type": "color",
   "css": "--gray-800",
   "values": {
    "Value": "#0B1017"
   },
   "resolved": {
    "Value": "#0B1017"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/900",
   "collection": "Primitives",
   "name": "gray/900",
   "type": "color",
   "css": "--gray-900",
   "values": {
    "Value": "#020810"
   },
   "resolved": {
    "Value": "#020810"
   },
   "description": ""
  },
  {
   "figma": "Primitives::gray/950",
   "collection": "Primitives",
   "name": "gray/950",
   "type": "color",
   "css": "--gray-950",
   "values": {
    "Value": "#020713"
   },
   "resolved": {
    "Value": "#020713"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/0",
   "collection": "Primitives",
   "name": "green/0",
   "type": "color",
   "css": "--green-0",
   "values": {
    "Value": "#F0FFF4"
   },
   "resolved": {
    "Value": "#F0FFF4"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/50",
   "collection": "Primitives",
   "name": "green/50",
   "type": "color",
   "css": "--green-50",
   "values": {
    "Value": "#F0FDF4"
   },
   "resolved": {
    "Value": "#F0FDF4"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/100",
   "collection": "Primitives",
   "name": "green/100",
   "type": "color",
   "css": "--green-100",
   "values": {
    "Value": "#DCFCE7"
   },
   "resolved": {
    "Value": "#DCFCE7"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/200",
   "collection": "Primitives",
   "name": "green/200",
   "type": "color",
   "css": "--green-200",
   "values": {
    "Value": "#BBF7D0"
   },
   "resolved": {
    "Value": "#BBF7D0"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/300",
   "collection": "Primitives",
   "name": "green/300",
   "type": "color",
   "css": "--green-300",
   "values": {
    "Value": "#86EFAC"
   },
   "resolved": {
    "Value": "#86EFAC"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/400",
   "collection": "Primitives",
   "name": "green/400",
   "type": "color",
   "css": "--green-400",
   "values": {
    "Value": "#4ADE80"
   },
   "resolved": {
    "Value": "#4ADE80"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/500",
   "collection": "Primitives",
   "name": "green/500",
   "type": "color",
   "css": "--green-500",
   "values": {
    "Value": "#22C55E"
   },
   "resolved": {
    "Value": "#22C55E"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/600",
   "collection": "Primitives",
   "name": "green/600",
   "type": "color",
   "css": "--green-600",
   "values": {
    "Value": "#16A34A"
   },
   "resolved": {
    "Value": "#16A34A"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/700",
   "collection": "Primitives",
   "name": "green/700",
   "type": "color",
   "css": "--green-700",
   "values": {
    "Value": "#15803D"
   },
   "resolved": {
    "Value": "#15803D"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/800",
   "collection": "Primitives",
   "name": "green/800",
   "type": "color",
   "css": "--green-800",
   "values": {
    "Value": "#166534"
   },
   "resolved": {
    "Value": "#166534"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/900",
   "collection": "Primitives",
   "name": "green/900",
   "type": "color",
   "css": "--green-900",
   "values": {
    "Value": "#14532D"
   },
   "resolved": {
    "Value": "#14532D"
   },
   "description": ""
  },
  {
   "figma": "Primitives::green/950",
   "collection": "Primitives",
   "name": "green/950",
   "type": "color",
   "css": "--green-950",
   "values": {
    "Value": "#032712"
   },
   "resolved": {
    "Value": "#032712"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/0",
   "collection": "Primitives",
   "name": "Orange/0",
   "type": "color",
   "css": "--orange-0",
   "values": {
    "Value": "#FFFCF9"
   },
   "resolved": {
    "Value": "#FFFCF9"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/50",
   "collection": "Primitives",
   "name": "Orange/50",
   "type": "color",
   "css": "--orange-50",
   "values": {
    "Value": "#FFF7ED"
   },
   "resolved": {
    "Value": "#FFF7ED"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/100",
   "collection": "Primitives",
   "name": "Orange/100",
   "type": "color",
   "css": "--orange-100",
   "values": {
    "Value": "#FFEDD5"
   },
   "resolved": {
    "Value": "#FFEDD5"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/200",
   "collection": "Primitives",
   "name": "Orange/200",
   "type": "color",
   "css": "--orange-200",
   "values": {
    "Value": "#FED7AA"
   },
   "resolved": {
    "Value": "#FED7AA"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/300",
   "collection": "Primitives",
   "name": "Orange/300",
   "type": "color",
   "css": "--orange-300",
   "values": {
    "Value": "#FDBA74"
   },
   "resolved": {
    "Value": "#FDBA74"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/400",
   "collection": "Primitives",
   "name": "Orange/400",
   "type": "color",
   "css": "--orange-400",
   "values": {
    "Value": "#FB923C"
   },
   "resolved": {
    "Value": "#FB923C"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/500",
   "collection": "Primitives",
   "name": "Orange/500",
   "type": "color",
   "css": "--orange-500",
   "values": {
    "Value": "#F97316"
   },
   "resolved": {
    "Value": "#F97316"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/600",
   "collection": "Primitives",
   "name": "Orange/600",
   "type": "color",
   "css": "--orange-600",
   "values": {
    "Value": "#EA580C"
   },
   "resolved": {
    "Value": "#EA580C"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/700",
   "collection": "Primitives",
   "name": "Orange/700",
   "type": "color",
   "css": "--orange-700",
   "values": {
    "Value": "#C2410C"
   },
   "resolved": {
    "Value": "#C2410C"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/800",
   "collection": "Primitives",
   "name": "Orange/800",
   "type": "color",
   "css": "--orange-800",
   "values": {
    "Value": "#9A3412"
   },
   "resolved": {
    "Value": "#9A3412"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/900",
   "collection": "Primitives",
   "name": "Orange/900",
   "type": "color",
   "css": "--orange-900",
   "values": {
    "Value": "#7C2D12"
   },
   "resolved": {
    "Value": "#7C2D12"
   },
   "description": ""
  },
  {
   "figma": "Primitives::Orange/950",
   "collection": "Primitives",
   "name": "Orange/950",
   "type": "color",
   "css": "--orange-950",
   "values": {
    "Value": "#431407"
   },
   "resolved": {
    "Value": "#431407"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/0",
   "collection": "Primitives",
   "name": "purple/0",
   "type": "color",
   "css": "--purple-0",
   "values": {
    "Value": "#FAF0FF"
   },
   "resolved": {
    "Value": "#FAF0FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/50",
   "collection": "Primitives",
   "name": "purple/50",
   "type": "color",
   "css": "--purple-50",
   "values": {
    "Value": "#FAF5FF"
   },
   "resolved": {
    "Value": "#FAF5FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/100",
   "collection": "Primitives",
   "name": "purple/100",
   "type": "color",
   "css": "--purple-100",
   "values": {
    "Value": "#F3E8FF"
   },
   "resolved": {
    "Value": "#F3E8FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/200",
   "collection": "Primitives",
   "name": "purple/200",
   "type": "color",
   "css": "--purple-200",
   "values": {
    "Value": "#E9D5FF"
   },
   "resolved": {
    "Value": "#E9D5FF"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/300",
   "collection": "Primitives",
   "name": "purple/300",
   "type": "color",
   "css": "--purple-300",
   "values": {
    "Value": "#D8B4FE"
   },
   "resolved": {
    "Value": "#D8B4FE"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/400",
   "collection": "Primitives",
   "name": "purple/400",
   "type": "color",
   "css": "--purple-400",
   "values": {
    "Value": "#C084FC"
   },
   "resolved": {
    "Value": "#C084FC"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/500",
   "collection": "Primitives",
   "name": "purple/500",
   "type": "color",
   "css": "--purple-500",
   "values": {
    "Value": "#A855F7"
   },
   "resolved": {
    "Value": "#A855F7"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/600",
   "collection": "Primitives",
   "name": "purple/600",
   "type": "color",
   "css": "--purple-600",
   "values": {
    "Value": "#9333EA"
   },
   "resolved": {
    "Value": "#9333EA"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/700",
   "collection": "Primitives",
   "name": "purple/700",
   "type": "color",
   "css": "--purple-700",
   "values": {
    "Value": "#7C3AED"
   },
   "resolved": {
    "Value": "#7C3AED"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/800",
   "collection": "Primitives",
   "name": "purple/800",
   "type": "color",
   "css": "--purple-800",
   "values": {
    "Value": "#6D28D9"
   },
   "resolved": {
    "Value": "#6D28D9"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/900",
   "collection": "Primitives",
   "name": "purple/900",
   "type": "color",
   "css": "--purple-900",
   "values": {
    "Value": "#581C87"
   },
   "resolved": {
    "Value": "#581C87"
   },
   "description": ""
  },
  {
   "figma": "Primitives::purple/950",
   "collection": "Primitives",
   "name": "purple/950",
   "type": "color",
   "css": "--purple-950",
   "values": {
    "Value": "#3B0764"
   },
   "resolved": {
    "Value": "#3B0764"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/0",
   "collection": "Primitives",
   "name": "red/0",
   "type": "color",
   "css": "--red-0",
   "values": {
    "Value": "#FFF5F5"
   },
   "resolved": {
    "Value": "#FFF5F5"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/50",
   "collection": "Primitives",
   "name": "red/50",
   "type": "color",
   "css": "--red-50",
   "values": {
    "Value": "#FEF2F2"
   },
   "resolved": {
    "Value": "#FEF2F2"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/100",
   "collection": "Primitives",
   "name": "red/100",
   "type": "color",
   "css": "--red-100",
   "values": {
    "Value": "#FEE2E2"
   },
   "resolved": {
    "Value": "#FEE2E2"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/200",
   "collection": "Primitives",
   "name": "red/200",
   "type": "color",
   "css": "--red-200",
   "values": {
    "Value": "#FECACA"
   },
   "resolved": {
    "Value": "#FECACA"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/300",
   "collection": "Primitives",
   "name": "red/300",
   "type": "color",
   "css": "--red-300",
   "values": {
    "Value": "#FCA5A5"
   },
   "resolved": {
    "Value": "#FCA5A5"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/400",
   "collection": "Primitives",
   "name": "red/400",
   "type": "color",
   "css": "--red-400",
   "values": {
    "Value": "#F87171"
   },
   "resolved": {
    "Value": "#F87171"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/500",
   "collection": "Primitives",
   "name": "red/500",
   "type": "color",
   "css": "--red-500",
   "values": {
    "Value": "#EF4444"
   },
   "resolved": {
    "Value": "#EF4444"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/600",
   "collection": "Primitives",
   "name": "red/600",
   "type": "color",
   "css": "--red-600",
   "values": {
    "Value": "#DC2626"
   },
   "resolved": {
    "Value": "#DC2626"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/700",
   "collection": "Primitives",
   "name": "red/700",
   "type": "color",
   "css": "--red-700",
   "values": {
    "Value": "#B91C1C"
   },
   "resolved": {
    "Value": "#B91C1C"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/800",
   "collection": "Primitives",
   "name": "red/800",
   "type": "color",
   "css": "--red-800",
   "values": {
    "Value": "#991B1B"
   },
   "resolved": {
    "Value": "#991B1B"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/900",
   "collection": "Primitives",
   "name": "red/900",
   "type": "color",
   "css": "--red-900",
   "values": {
    "Value": "#7F1D1D"
   },
   "resolved": {
    "Value": "#7F1D1D"
   },
   "description": ""
  },
  {
   "figma": "Primitives::red/950",
   "collection": "Primitives",
   "name": "red/950",
   "type": "color",
   "css": "--red-950",
   "values": {
    "Value": "#450A0A"
   },
   "resolved": {
    "Value": "#450A0A"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/0",
   "collection": "Primitives",
   "name": "yellow/0",
   "type": "color",
   "css": "--yellow-0",
   "values": {
    "Value": "#FFFEF5"
   },
   "resolved": {
    "Value": "#FFFEF5"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/50",
   "collection": "Primitives",
   "name": "yellow/50",
   "type": "color",
   "css": "--yellow-50",
   "values": {
    "Value": "#FFFBEB"
   },
   "resolved": {
    "Value": "#FFFBEB"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/100",
   "collection": "Primitives",
   "name": "yellow/100",
   "type": "color",
   "css": "--yellow-100",
   "values": {
    "Value": "#FEF3C7"
   },
   "resolved": {
    "Value": "#FEF3C7"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/200",
   "collection": "Primitives",
   "name": "yellow/200",
   "type": "color",
   "css": "--yellow-200",
   "values": {
    "Value": "#FDE68A"
   },
   "resolved": {
    "Value": "#FDE68A"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/300",
   "collection": "Primitives",
   "name": "yellow/300",
   "type": "color",
   "css": "--yellow-300",
   "values": {
    "Value": "#FCD34D"
   },
   "resolved": {
    "Value": "#FCD34D"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/400",
   "collection": "Primitives",
   "name": "yellow/400",
   "type": "color",
   "css": "--yellow-400",
   "values": {
    "Value": "#FBBF24"
   },
   "resolved": {
    "Value": "#FBBF24"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/500",
   "collection": "Primitives",
   "name": "yellow/500",
   "type": "color",
   "css": "--yellow-500",
   "values": {
    "Value": "#F59E0B"
   },
   "resolved": {
    "Value": "#F59E0B"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/600",
   "collection": "Primitives",
   "name": "yellow/600",
   "type": "color",
   "css": "--yellow-600",
   "values": {
    "Value": "#D97706"
   },
   "resolved": {
    "Value": "#D97706"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/700",
   "collection": "Primitives",
   "name": "yellow/700",
   "type": "color",
   "css": "--yellow-700",
   "values": {
    "Value": "#B45309"
   },
   "resolved": {
    "Value": "#B45309"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/800",
   "collection": "Primitives",
   "name": "yellow/800",
   "type": "color",
   "css": "--yellow-800",
   "values": {
    "Value": "#92400E"
   },
   "resolved": {
    "Value": "#92400E"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/900",
   "collection": "Primitives",
   "name": "yellow/900",
   "type": "color",
   "css": "--yellow-900",
   "values": {
    "Value": "#78350F"
   },
   "resolved": {
    "Value": "#78350F"
   },
   "description": ""
  },
  {
   "figma": "Primitives::yellow/950",
   "collection": "Primitives",
   "name": "yellow/950",
   "type": "color",
   "css": "--yellow-950",
   "values": {
    "Value": "#451A03"
   },
   "resolved": {
    "Value": "#451A03"
   },
   "description": ""
  },
  {
   "figma": "Radius::radius/2xl",
   "collection": "Radius",
   "name": "radius/2xl",
   "type": "dimension",
   "css": "--radius-2xl",
   "values": {
    "Default": 16
   },
   "resolved": {},
   "description": "Modals"
  },
  {
   "figma": "Radius::radius/3xl",
   "collection": "Radius",
   "name": "radius/3xl",
   "type": "dimension",
   "css": "--radius-3xl",
   "values": {
    "Default": 24
   },
   "resolved": {},
   "description": "Extra large"
  },
  {
   "figma": "Radius::radius/base",
   "collection": "Radius",
   "name": "radius/base",
   "type": "dimension",
   "css": "--radius-base",
   "values": {
    "Default": 4
   },
   "resolved": {},
   "description": "Default"
  },
  {
   "figma": "Radius::radius/full",
   "collection": "Radius",
   "name": "radius/full",
   "type": "dimension",
   "css": "--radius-full",
   "values": {
    "Default": 9999
   },
   "resolved": {},
   "description": "Pills, avatars"
  },
  {
   "figma": "Radius::radius/lg",
   "collection": "Radius",
   "name": "radius/lg",
   "type": "dimension",
   "css": "--radius-lg",
   "values": {
    "Default": 8
   },
   "resolved": {},
   "description": "Cards, inputs"
  },
  {
   "figma": "Radius::radius/md",
   "collection": "Radius",
   "name": "radius/md",
   "type": "dimension",
   "css": "--radius-md",
   "values": {
    "Default": 6
   },
   "resolved": {},
   "description": "Small cards"
  },
  {
   "figma": "Radius::radius/none",
   "collection": "Radius",
   "name": "radius/none",
   "type": "dimension",
   "css": "--radius-none",
   "values": {
    "Default": 0
   },
   "resolved": {},
   "description": "No rounding"
  },
  {
   "figma": "Radius::radius/sm",
   "collection": "Radius",
   "name": "radius/sm",
   "type": "dimension",
   "css": "--radius-sm",
   "values": {
    "Default": 2
   },
   "resolved": {},
   "description": "Subtle"
  },
  {
   "figma": "Radius::radius/xl",
   "collection": "Radius",
   "name": "radius/xl",
   "type": "dimension",
   "css": "--radius-xl",
   "values": {
    "Default": 12
   },
   "resolved": {},
   "description": "Panels"
  },
  {
   "figma": "Semantic::color/bg/error",
   "collection": "Semantic",
   "name": "color/bg/error",
   "type": "color",
   "css": "--color-bg-error",
   "values": {
    "Dark": {
     "alias": "Primitives::red/950"
    },
    "Light": {
     "alias": "Primitives::red/50"
    }
   },
   "resolved": {
    "Dark": "#450A0A",
    "Light": "#FEF2F2"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/info",
   "collection": "Semantic",
   "name": "color/bg/info",
   "type": "color",
   "css": "--color-bg-info",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/950"
    },
    "Light": {
     "alias": "Primitives::blue/50"
    }
   },
   "resolved": {
    "Dark": "#172554",
    "Light": "#EFF6FF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/inverse",
   "collection": "Semantic",
   "name": "color/bg/inverse",
   "type": "color",
   "css": "--color-bg-inverse",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    },
    "Light": {
     "alias": "Primitives::gray/900"
    }
   },
   "resolved": {
    "Dark": "#F9FAFB",
    "Light": "#020810"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/muted",
   "collection": "Semantic",
   "name": "color/bg/muted",
   "type": "color",
   "css": "--color-bg-muted",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    },
    "Light": {
     "alias": "Primitives::gray/100"
    }
   },
   "resolved": {
    "Dark": "#374151",
    "Light": "#F3F4F6"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/overlay",
   "collection": "Semantic",
   "name": "color/bg/overlay",
   "type": "color",
   "css": "--color-bg-overlay",
   "values": {
    "Dark": {
     "alias": "Primitives::alpha/black-70"
    },
    "Light": {
     "alias": "Primitives::alpha/black-50"
    }
   },
   "resolved": {
    "Dark": "#000000B2",
    "Light": "#02081080"
   },
   "description": "Modal/drawer scrim (50% gray-900 light, 70% black dark)."
  },
  {
   "figma": "Semantic::color/bg/primary",
   "collection": "Semantic",
   "name": "color/bg/primary",
   "type": "color",
   "css": "--color-bg-primary",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    },
    "Light": {
     "alias": "Primitives::black and white/white"
    }
   },
   "resolved": {
    "Dark": "#020713",
    "Light": "#FFFFFF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/secondary",
   "collection": "Semantic",
   "name": "color/bg/secondary",
   "type": "color",
   "css": "--color-bg-secondary",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    },
    "Light": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#0B1017",
    "Light": "#F9FAFB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/subtle",
   "collection": "Semantic",
   "name": "color/bg/subtle",
   "type": "color",
   "css": "--color-bg-subtle",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    },
    "Light": {
     "alias": "Primitives::gray/200"
    }
   },
   "resolved": {
    "Dark": "#0B1017",
    "Light": "#E5E7EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/success",
   "collection": "Semantic",
   "name": "color/bg/success",
   "type": "color",
   "css": "--color-bg-success",
   "values": {
    "Dark": {
     "alias": "Primitives::green/950"
    },
    "Light": {
     "alias": "Primitives::green/50"
    }
   },
   "resolved": {
    "Dark": "#032712",
    "Light": "#F0FDF4"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/bg/warning",
   "collection": "Semantic",
   "name": "color/bg/warning",
   "type": "color",
   "css": "--color-bg-warning",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/950"
    },
    "Light": {
     "alias": "Primitives::yellow/50"
    }
   },
   "resolved": {
    "Dark": "#451A03",
    "Light": "#FFFBEB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/Dark",
   "collection": "Semantic",
   "name": "color/border/Dark",
   "type": "color",
   "css": "--color-border-dark",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/100"
    },
    "Light": {
     "alias": "Primitives::gray/800"
    }
   },
   "resolved": {
    "Dark": "#F3F4F6",
    "Light": "#0B1017"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/default",
   "collection": "Semantic",
   "name": "color/border/default",
   "type": "color",
   "css": "--color-border-default",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    },
    "Light": {
     "alias": "Primitives::gray/200"
    }
   },
   "resolved": {
    "Dark": "#374151",
    "Light": "#E5E7EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/error",
   "collection": "Semantic",
   "name": "color/border/error",
   "type": "color",
   "css": "--color-border-error",
   "values": {
    "Dark": {
     "alias": "Primitives::red/500"
    },
    "Light": {
     "alias": "Primitives::red/500"
    }
   },
   "resolved": {
    "Dark": "#EF4444",
    "Light": "#EF4444"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/focus",
   "collection": "Semantic",
   "name": "color/border/focus",
   "type": "color",
   "css": "--color-border-focus",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/500"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#3B82F6"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/input",
   "collection": "Semantic",
   "name": "color/border/input",
   "type": "color",
   "css": "--color-border-input",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/500"
    },
    "Light": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#6B7280",
    "Light": "#9CA3AF"
   },
   "description": "Border of form controls at rest (inputs, checkbox, radio). Meets ~3:1 against bg/primary."
  },
  {
   "figma": "Semantic::color/border/inverse",
   "collection": "Semantic",
   "name": "color/border/inverse",
   "type": "color",
   "css": "--color-border-inverse",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/300"
    },
    "Light": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#D1D5DB",
    "Light": "#374151"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/muted",
   "collection": "Semantic",
   "name": "color/border/muted",
   "type": "color",
   "css": "--color-border-muted",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    },
    "Light": {
     "alias": "Primitives::gray/100"
    }
   },
   "resolved": {
    "Dark": "#0B1017",
    "Light": "#F3F4F6"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/strong",
   "collection": "Semantic",
   "name": "color/border/strong",
   "type": "color",
   "css": "--color-border-strong",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/600"
    },
    "Light": {
     "alias": "Primitives::gray/300"
    }
   },
   "resolved": {
    "Dark": "#4B5563",
    "Light": "#D1D5DB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/success",
   "collection": "Semantic",
   "name": "color/border/success",
   "type": "color",
   "css": "--color-border-success",
   "values": {
    "Dark": {
     "alias": "Primitives::green/500"
    },
    "Light": {
     "alias": "Primitives::green/500"
    }
   },
   "resolved": {
    "Dark": "#22C55E",
    "Light": "#22C55E"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/border/warning",
   "collection": "Semantic",
   "name": "color/border/warning",
   "type": "color",
   "css": "--color-border-warning",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/500"
    },
    "Light": {
     "alias": "Primitives::yellow/500"
    }
   },
   "resolved": {
    "Dark": "#F59E0B",
    "Light": "#F59E0B"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/bg",
   "collection": "Semantic",
   "name": "color/btn/danger/bg",
   "type": "color",
   "css": "--color-btn-danger-bg",
   "values": {
    "Dark": {
     "alias": "Primitives::red/600"
    },
    "Light": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#DC2626",
    "Light": "#DC2626"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/bg-active",
   "collection": "Semantic",
   "name": "color/btn/danger/bg-active",
   "type": "color",
   "css": "--color-btn-danger-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::red/400"
    },
    "Light": {
     "alias": "Primitives::red/800"
    }
   },
   "resolved": {
    "Dark": "#F87171",
    "Light": "#991B1B"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/danger/bg-hover",
   "type": "color",
   "css": "--color-btn-danger-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::red/500"
    },
    "Light": {
     "alias": "Primitives::red/700"
    }
   },
   "resolved": {
    "Dark": "#EF4444",
    "Light": "#B91C1C"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/border",
   "collection": "Semantic",
   "name": "color/btn/danger/border",
   "type": "color",
   "css": "--color-btn-danger-border",
   "values": {
    "Dark": {
     "alias": "Primitives::red/600"
    },
    "Light": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#DC2626",
    "Light": "#DC2626"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/light",
   "collection": "Semantic",
   "name": "color/btn/danger/light",
   "type": "color",
   "css": "--color-btn-danger-light",
   "values": {
    "Dark": {
     "alias": "Primitives::red/950"
    },
    "Light": {
     "alias": "Primitives::red/50"
    }
   },
   "resolved": {
    "Dark": "#450A0A",
    "Light": "#FEF2F2"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/danger/text",
   "collection": "Semantic",
   "name": "color/btn/danger/text",
   "type": "color",
   "css": "--color-btn-danger-text",
   "values": {
    "Dark": {
     "alias": "Primitives::red/200"
    },
    "Light": {
     "alias": "Primitives::red/900"
    }
   },
   "resolved": {
    "Dark": "#FECACA",
    "Light": "#7F1D1D"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/bg",
   "collection": "Semantic",
   "name": "color/btn/Info/bg",
   "type": "color",
   "css": "--color-btn-info-bg",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/500"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#3B82F6",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/bg-active",
   "collection": "Semantic",
   "name": "color/btn/Info/bg-active",
   "type": "color",
   "css": "--color-btn-info-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/800"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#1E40AF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/Info/bg-hover",
   "type": "color",
   "css": "--color-btn-info-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/700"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#1D4ED8"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/border",
   "collection": "Semantic",
   "name": "color/btn/Info/border",
   "type": "color",
   "css": "--color-btn-info-border",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/500"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#3B82F6",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/light",
   "collection": "Semantic",
   "name": "color/btn/Info/light",
   "type": "color",
   "css": "--color-btn-info-light",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/950"
    },
    "Light": {
     "alias": "Primitives::blue/50"
    }
   },
   "resolved": {
    "Dark": "#172554",
    "Light": "#EFF6FF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Info/text",
   "collection": "Semantic",
   "name": "color/btn/Info/text",
   "type": "color",
   "css": "--color-btn-info-text",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/900"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#1E3A8A"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Neutral/bg-active",
   "collection": "Semantic",
   "name": "color/btn/Neutral/bg-active",
   "type": "color",
   "css": "--color-btn-neutral-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    },
    "Light": {
     "alias": "Primitives::gray/200"
    }
   },
   "resolved": {
    "Dark": "#374151",
    "Light": "#E5E7EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Neutral/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/Neutral/bg-hover",
   "type": "color",
   "css": "--color-btn-neutral-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    },
    "Light": {
     "alias": "Primitives::gray/100"
    }
   },
   "resolved": {
    "Dark": "#0B1017",
    "Light": "#F3F4F6"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Neutral/text",
   "collection": "Semantic",
   "name": "color/btn/Neutral/text",
   "type": "color",
   "css": "--color-btn-neutral-text",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/300"
    },
    "Light": {
     "alias": "Primitives::gray/600"
    }
   },
   "resolved": {
    "Dark": "#D1D5DB",
    "Light": "#4B5563"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/bg 2",
   "collection": "Semantic",
   "name": "color/btn/Primary/bg 2",
   "type": "color",
   "css": "--color-btn-primary-bg-2",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/bg-active 2",
   "collection": "Semantic",
   "name": "color/btn/Primary/bg-active 2",
   "type": "color",
   "css": "--color-btn-primary-bg-active-2",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/500"
    },
    "Light": {
     "alias": "Primitives::blue/800"
    }
   },
   "resolved": {
    "Dark": "#3B82F6",
    "Light": "#1E40AF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/bg-hover 2",
   "collection": "Semantic",
   "name": "color/btn/Primary/bg-hover 2",
   "type": "color",
   "css": "--color-btn-primary-bg-hover-2",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/700"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#1D4ED8"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/border 2",
   "collection": "Semantic",
   "name": "color/btn/Primary/border 2",
   "type": "color",
   "css": "--color-btn-primary-border-2",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/Light",
   "collection": "Semantic",
   "name": "color/btn/Primary/Light",
   "type": "color",
   "css": "--color-btn-primary-light",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/50"
    },
    "Light": {
     "alias": "Primitives::blue/100"
    }
   },
   "resolved": {
    "Dark": "#EFF6FF",
    "Light": "#DBEAFE"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/Primary/text 2",
   "collection": "Semantic",
   "name": "color/btn/Primary/text 2",
   "type": "color",
   "css": "--color-btn-primary-text-2",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/900"
    },
    "Light": {
     "alias": "Primitives::gray/0"
    }
   },
   "resolved": {
    "Dark": "#020810",
    "Light": "#FAFAFA"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/secondary/bg",
   "collection": "Semantic",
   "name": "color/btn/secondary/bg",
   "type": "color",
   "css": "--color-btn-secondary-bg",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    },
    "Light": {
     "alias": "Primitives::black and white/white"
    }
   },
   "resolved": {
    "Dark": "#0B1017",
    "Light": "#FFFFFF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/secondary/bg-active",
   "collection": "Semantic",
   "name": "color/btn/secondary/bg-active",
   "type": "color",
   "css": "--color-btn-secondary-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/600"
    },
    "Light": {
     "alias": "Primitives::gray/100"
    }
   },
   "resolved": {
    "Dark": "#4B5563",
    "Light": "#F3F4F6"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/secondary/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/secondary/bg-hover",
   "type": "color",
   "css": "--color-btn-secondary-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    },
    "Light": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#374151",
    "Light": "#F9FAFB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/secondary/border",
   "collection": "Semantic",
   "name": "color/btn/secondary/border",
   "type": "color",
   "css": "--color-btn-secondary-border",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/600"
    },
    "Light": {
     "alias": "Primitives::gray/300"
    }
   },
   "resolved": {
    "Dark": "#4B5563",
    "Light": "#D1D5DB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/secondary/text",
   "collection": "Semantic",
   "name": "color/btn/secondary/text",
   "type": "color",
   "css": "--color-btn-secondary-text",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/200"
    },
    "Light": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#E5E7EB",
    "Light": "#374151"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/bg",
   "collection": "Semantic",
   "name": "color/btn/success/bg",
   "type": "color",
   "css": "--color-btn-success-bg",
   "values": {
    "Dark": {
     "alias": "Primitives::green/600"
    },
    "Light": {
     "alias": "Primitives::green/600"
    }
   },
   "resolved": {
    "Dark": "#16A34A",
    "Light": "#16A34A"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/bg-active",
   "collection": "Semantic",
   "name": "color/btn/success/bg-active",
   "type": "color",
   "css": "--color-btn-success-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::green/400"
    },
    "Light": {
     "alias": "Primitives::green/800"
    }
   },
   "resolved": {
    "Dark": "#4ADE80",
    "Light": "#166534"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/success/bg-hover",
   "type": "color",
   "css": "--color-btn-success-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::green/500"
    },
    "Light": {
     "alias": "Primitives::green/700"
    }
   },
   "resolved": {
    "Dark": "#22C55E",
    "Light": "#15803D"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/border",
   "collection": "Semantic",
   "name": "color/btn/success/border",
   "type": "color",
   "css": "--color-btn-success-border",
   "values": {
    "Dark": {
     "alias": "Primitives::green/600"
    },
    "Light": {
     "alias": "Primitives::green/600"
    }
   },
   "resolved": {
    "Dark": "#16A34A",
    "Light": "#16A34A"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/light",
   "collection": "Semantic",
   "name": "color/btn/success/light",
   "type": "color",
   "css": "--color-btn-success-light",
   "values": {
    "Dark": {
     "alias": "Primitives::green/950"
    },
    "Light": {
     "alias": "Primitives::green/50"
    }
   },
   "resolved": {
    "Dark": "#032712",
    "Light": "#F0FDF4"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/success/text",
   "collection": "Semantic",
   "name": "color/btn/success/text",
   "type": "color",
   "css": "--color-btn-success-text",
   "values": {
    "Dark": {
     "alias": "Primitives::green/200"
    },
    "Light": {
     "alias": "Primitives::green/900"
    }
   },
   "resolved": {
    "Dark": "#BBF7D0",
    "Light": "#14532D"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/bg",
   "collection": "Semantic",
   "name": "color/btn/warning/bg",
   "type": "color",
   "css": "--color-btn-warning-bg",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/500"
    },
    "Light": {
     "alias": "Primitives::yellow/500"
    }
   },
   "resolved": {
    "Dark": "#F59E0B",
    "Light": "#F59E0B"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/bg-active",
   "collection": "Semantic",
   "name": "color/btn/warning/bg-active",
   "type": "color",
   "css": "--color-btn-warning-bg-active",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/300"
    },
    "Light": {
     "alias": "Primitives::yellow/700"
    }
   },
   "resolved": {
    "Dark": "#FCD34D",
    "Light": "#B45309"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/bg-hover",
   "collection": "Semantic",
   "name": "color/btn/warning/bg-hover",
   "type": "color",
   "css": "--color-btn-warning-bg-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/400"
    },
    "Light": {
     "alias": "Primitives::yellow/600"
    }
   },
   "resolved": {
    "Dark": "#FBBF24",
    "Light": "#D97706"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/border",
   "collection": "Semantic",
   "name": "color/btn/warning/border",
   "type": "color",
   "css": "--color-btn-warning-border",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/500"
    },
    "Light": {
     "alias": "Primitives::yellow/500"
    }
   },
   "resolved": {
    "Dark": "#F59E0B",
    "Light": "#F59E0B"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/Light",
   "collection": "Semantic",
   "name": "color/btn/warning/Light",
   "type": "color",
   "css": "--color-btn-warning-light",
   "values": {
    "Dark": {
     "alias": "Primitives::Orange/950"
    },
    "Light": {
     "alias": "Primitives::yellow/50"
    }
   },
   "resolved": {
    "Dark": "#431407",
    "Light": "#FFFBEB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/btn/warning/text",
   "collection": "Semantic",
   "name": "color/btn/warning/text",
   "type": "color",
   "css": "--color-btn-warning-text",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/300"
    },
    "Light": {
     "alias": "Primitives::yellow/900"
    }
   },
   "resolved": {
    "Dark": "#FCD34D",
    "Light": "#78350F"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/icon/brand",
   "collection": "Semantic",
   "name": "color/icon/brand",
   "type": "color",
   "css": "--color-icon-brand",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#2563EB"
   },
   "description": "Brand / interactive icons"
  },
  {
   "figma": "Semantic::color/icon/default",
   "collection": "Semantic",
   "name": "color/icon/default",
   "type": "color",
   "css": "--color-icon-default",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/300"
    },
    "Light": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#D1D5DB",
    "Light": "#374151"
   },
   "description": "Default icon color"
  },
  {
   "figma": "Semantic::color/icon/error",
   "collection": "Semantic",
   "name": "color/icon/error",
   "type": "color",
   "css": "--color-icon-error",
   "values": {
    "Dark": {
     "alias": "Primitives::red/400"
    },
    "Light": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#F87171",
    "Light": "#DC2626"
   },
   "description": "Error status icons"
  },
  {
   "figma": "Semantic::color/icon/info",
   "collection": "Semantic",
   "name": "color/icon/info",
   "type": "color",
   "css": "--color-icon-info",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#2563EB"
   },
   "description": "Info status icons"
  },
  {
   "figma": "Semantic::color/icon/inverse",
   "collection": "Semantic",
   "name": "color/icon/inverse",
   "type": "color",
   "css": "--color-icon-inverse",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/900"
    },
    "Light": {
     "alias": "Primitives::black and white/white"
    }
   },
   "resolved": {
    "Dark": "#020810",
    "Light": "#FFFFFF"
   },
   "description": "Icons on solid brand or dark surfaces"
  },
  {
   "figma": "Semantic::color/icon/muted",
   "collection": "Semantic",
   "name": "color/icon/muted",
   "type": "color",
   "css": "--color-icon-muted",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/500"
    },
    "Light": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#6B7280",
    "Light": "#9CA3AF"
   },
   "description": "Decorative / placeholder icons"
  },
  {
   "figma": "Semantic::color/icon/strong",
   "collection": "Semantic",
   "name": "color/icon/strong",
   "type": "color",
   "css": "--color-icon-strong",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    },
    "Light": {
     "alias": "Primitives::gray/900"
    }
   },
   "resolved": {
    "Dark": "#F9FAFB",
    "Light": "#020810"
   },
   "description": "High-emphasis icons (close, primary actions)"
  },
  {
   "figma": "Semantic::color/icon/success",
   "collection": "Semantic",
   "name": "color/icon/success",
   "type": "color",
   "css": "--color-icon-success",
   "values": {
    "Dark": {
     "alias": "Primitives::green/400"
    },
    "Light": {
     "alias": "Primitives::green/600"
    }
   },
   "resolved": {
    "Dark": "#4ADE80",
    "Light": "#16A34A"
   },
   "description": "Success status icons"
  },
  {
   "figma": "Semantic::color/icon/warning",
   "collection": "Semantic",
   "name": "color/icon/warning",
   "type": "color",
   "css": "--color-icon-warning",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/300"
    },
    "Light": {
     "alias": "Primitives::yellow/600"
    }
   },
   "resolved": {
    "Dark": "#FCD34D",
    "Light": "#D97706"
   },
   "description": "Warning status icons"
  },
  {
   "figma": "Semantic::color/text/disabled",
   "collection": "Semantic",
   "name": "color/text/disabled",
   "type": "color",
   "css": "--color-text-disabled",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/600"
    },
    "Light": {
     "alias": "Primitives::gray/300"
    }
   },
   "resolved": {
    "Dark": "#4B5563",
    "Light": "#D1D5DB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/error",
   "collection": "Semantic",
   "name": "color/text/error",
   "type": "color",
   "css": "--color-text-error",
   "values": {
    "Dark": {
     "alias": "Primitives::red/400"
    },
    "Light": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#F87171",
    "Light": "#DC2626"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/info",
   "collection": "Semantic",
   "name": "color/text/info",
   "type": "color",
   "css": "--color-text-info",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/inverse",
   "collection": "Semantic",
   "name": "color/text/inverse",
   "type": "color",
   "css": "--color-text-inverse",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/900"
    },
    "Light": {
     "alias": "Primitives::black and white/white"
    }
   },
   "resolved": {
    "Dark": "#020810",
    "Light": "#FFFFFF"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/link",
   "collection": "Semantic",
   "name": "color/text/link",
   "type": "color",
   "css": "--color-text-link",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    },
    "Light": {
     "alias": "Primitives::blue/600"
    }
   },
   "resolved": {
    "Dark": "#60A5FA",
    "Light": "#2563EB"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/link-hover",
   "collection": "Semantic",
   "name": "color/text/link-hover",
   "type": "color",
   "css": "--color-text-link-hover",
   "values": {
    "Dark": {
     "alias": "Primitives::blue/300"
    },
    "Light": {
     "alias": "Primitives::blue/700"
    }
   },
   "resolved": {
    "Dark": "#93C5FD",
    "Light": "#1D4ED8"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/muted",
   "collection": "Semantic",
   "name": "color/text/muted",
   "type": "color",
   "css": "--color-text-muted",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    },
    "Light": {
     "alias": "Primitives::gray/500"
    }
   },
   "resolved": {
    "Dark": "#9CA3AF",
    "Light": "#6B7280"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/placeholder",
   "collection": "Semantic",
   "name": "color/text/placeholder",
   "type": "color",
   "css": "--color-text-placeholder",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    },
    "Light": {
     "alias": "Primitives::gray/500"
    }
   },
   "resolved": {
    "Dark": "#9CA3AF",
    "Light": "#6B7280"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/primary",
   "collection": "Semantic",
   "name": "color/text/primary",
   "type": "color",
   "css": "--color-text-primary",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    },
    "Light": {
     "alias": "Primitives::gray/900"
    }
   },
   "resolved": {
    "Dark": "#F9FAFB",
    "Light": "#020810"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/secondary",
   "collection": "Semantic",
   "name": "color/text/secondary",
   "type": "color",
   "css": "--color-text-secondary",
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    },
    "Light": {
     "alias": "Primitives::gray/600"
    }
   },
   "resolved": {
    "Dark": "#9CA3AF",
    "Light": "#4B5563"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/success",
   "collection": "Semantic",
   "name": "color/text/success",
   "type": "color",
   "css": "--color-text-success",
   "values": {
    "Dark": {
     "alias": "Primitives::green/400"
    },
    "Light": {
     "alias": "Primitives::green/600"
    }
   },
   "resolved": {
    "Dark": "#4ADE80",
    "Light": "#16A34A"
   },
   "description": ""
  },
  {
   "figma": "Semantic::color/text/warning",
   "collection": "Semantic",
   "name": "color/text/warning",
   "type": "color",
   "css": "--color-text-warning",
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/300"
    },
    "Light": {
     "alias": "Primitives::yellow/600"
    }
   },
   "resolved": {
    "Dark": "#FCD34D",
    "Light": "#D97706"
   },
   "description": ""
  },
  {
   "figma": "Spacing::space/0",
   "collection": "Spacing",
   "name": "space/0",
   "type": "dimension",
   "css": "--space-0",
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/1",
   "collection": "Spacing",
   "name": "space/1",
   "type": "dimension",
   "css": "--space-1",
   "values": {
    "Desktop": 4,
    "iPad": 4,
    "Mobile": 4
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/2",
   "collection": "Spacing",
   "name": "space/2",
   "type": "dimension",
   "css": "--space-2",
   "values": {
    "Desktop": 8,
    "iPad": 8,
    "Mobile": 8
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/3",
   "collection": "Spacing",
   "name": "space/3",
   "type": "dimension",
   "css": "--space-3",
   "values": {
    "Desktop": 12,
    "iPad": 12,
    "Mobile": 12
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/4",
   "collection": "Spacing",
   "name": "space/4",
   "type": "dimension",
   "css": "--space-4",
   "values": {
    "Desktop": 16,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/5",
   "collection": "Spacing",
   "name": "space/5",
   "type": "dimension",
   "css": "--space-5",
   "values": {
    "Desktop": 20,
    "iPad": 20,
    "Mobile": 16
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/6",
   "collection": "Spacing",
   "name": "space/6",
   "type": "dimension",
   "css": "--space-6",
   "values": {
    "Desktop": 24,
    "iPad": 22,
    "Mobile": 18
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/7",
   "collection": "Spacing",
   "name": "space/7",
   "type": "dimension",
   "css": "--space-7",
   "values": {
    "Desktop": 28,
    "iPad": 26,
    "Mobile": 22
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/8",
   "collection": "Spacing",
   "name": "space/8",
   "type": "dimension",
   "css": "--space-8",
   "values": {
    "Desktop": 32,
    "iPad": 28,
    "Mobile": 24
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/9",
   "collection": "Spacing",
   "name": "space/9",
   "type": "dimension",
   "css": "--space-9",
   "values": {
    "Desktop": 36,
    "iPad": 32,
    "Mobile": 26
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/10",
   "collection": "Spacing",
   "name": "space/10",
   "type": "dimension",
   "css": "--space-10",
   "values": {
    "Desktop": 40,
    "iPad": 36,
    "Mobile": 28
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/11",
   "collection": "Spacing",
   "name": "space/11",
   "type": "dimension",
   "css": "--space-11",
   "values": {
    "Desktop": 44,
    "iPad": 40,
    "Mobile": 32
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/12",
   "collection": "Spacing",
   "name": "space/12",
   "type": "dimension",
   "css": "--space-12",
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 32
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/14",
   "collection": "Spacing",
   "name": "space/14",
   "type": "dimension",
   "css": "--space-14",
   "values": {
    "Desktop": 56,
    "iPad": 48,
    "Mobile": 36
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/16",
   "collection": "Spacing",
   "name": "space/16",
   "type": "dimension",
   "css": "--space-16",
   "values": {
    "Desktop": 64,
    "iPad": 52,
    "Mobile": 40
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/20",
   "collection": "Spacing",
   "name": "space/20",
   "type": "dimension",
   "css": "--space-20",
   "values": {
    "Desktop": 80,
    "iPad": 64,
    "Mobile": 48
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/24",
   "collection": "Spacing",
   "name": "space/24",
   "type": "dimension",
   "css": "--space-24",
   "values": {
    "Desktop": 96,
    "iPad": 76,
    "Mobile": 56
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/28",
   "collection": "Spacing",
   "name": "space/28",
   "type": "dimension",
   "css": "--space-28",
   "values": {
    "Desktop": 112,
    "iPad": 88,
    "Mobile": 64
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/32",
   "collection": "Spacing",
   "name": "space/32",
   "type": "dimension",
   "css": "--space-32",
   "values": {
    "Desktop": 128,
    "iPad": 96,
    "Mobile": 72
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/36",
   "collection": "Spacing",
   "name": "space/36",
   "type": "dimension",
   "css": "--space-36",
   "values": {
    "Desktop": 144,
    "iPad": 112,
    "Mobile": 80
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/40",
   "collection": "Spacing",
   "name": "space/40",
   "type": "dimension",
   "css": "--space-40",
   "values": {
    "Desktop": 160,
    "iPad": 120,
    "Mobile": 88
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/48",
   "collection": "Spacing",
   "name": "space/48",
   "type": "dimension",
   "css": "--space-48",
   "values": {
    "Desktop": 192,
    "iPad": 144,
    "Mobile": 96
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/56",
   "collection": "Spacing",
   "name": "space/56",
   "type": "dimension",
   "css": "--space-56",
   "values": {
    "Desktop": 224,
    "iPad": 168,
    "Mobile": 104
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Spacing::space/64",
   "collection": "Spacing",
   "name": "space/64",
   "type": "dimension",
   "css": "--space-64",
   "values": {
    "Desktop": 256,
    "iPad": 192,
    "Mobile": 112
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font Family/Font Family",
   "collection": "Typography",
   "name": "Font Family/Font Family",
   "type": "string",
   "css": "--font-family-font-family",
   "values": {
    "Desktop": "Poppins",
    "iPad": "Poppins",
    "Mobile": "Poppins"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font weight/Bold",
   "collection": "Typography",
   "name": "Font weight/Bold",
   "type": "string",
   "css": "--font-weight-bold",
   "values": {
    "Desktop": "Bold",
    "iPad": "Bold",
    "Mobile": "Bold"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font weight/Light",
   "collection": "Typography",
   "name": "Font weight/Light",
   "type": "string",
   "css": "--font-weight-light",
   "values": {
    "Desktop": "Light",
    "iPad": "Light",
    "Mobile": "Light"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font weight/Medium",
   "collection": "Typography",
   "name": "Font weight/Medium",
   "type": "string",
   "css": "--font-weight-medium",
   "values": {
    "Desktop": "Medium",
    "iPad": "Medium",
    "Mobile": "Medium"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font weight/Regular",
   "collection": "Typography",
   "name": "Font weight/Regular",
   "type": "string",
   "css": "--font-weight-regular",
   "values": {
    "Desktop": "Regular",
    "iPad": "Regular",
    "Mobile": "Regular"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::Font weight/Semi-Bold",
   "collection": "Typography",
   "name": "Font weight/Semi-Bold",
   "type": "string",
   "css": "--font-weight-semi-bold",
   "values": {
    "Desktop": "SemiBold",
    "iPad": "SemiBold",
    "Mobile": "SemiBold"
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/2xl",
   "collection": "Typography",
   "name": "font-size/2xl",
   "type": "dimension",
   "css": "--font-size-2xl",
   "values": {
    "Desktop": 24,
    "iPad": 22,
    "Mobile": 20
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/3xl",
   "collection": "Typography",
   "name": "font-size/3xl",
   "type": "dimension",
   "css": "--font-size-3xl",
   "values": {
    "Desktop": 28,
    "iPad": 24,
    "Mobile": 24
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/4xl",
   "collection": "Typography",
   "name": "font-size/4xl",
   "type": "dimension",
   "css": "--font-size-4xl",
   "values": {
    "Desktop": 32,
    "iPad": 28,
    "Mobile": 28
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/5xl",
   "collection": "Typography",
   "name": "font-size/5xl",
   "type": "dimension",
   "css": "--font-size-5xl",
   "values": {
    "Desktop": 40,
    "iPad": 36,
    "Mobile": 32
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/6xl",
   "collection": "Typography",
   "name": "font-size/6xl",
   "type": "dimension",
   "css": "--font-size-6xl",
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 40
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/base",
   "collection": "Typography",
   "name": "font-size/base",
   "type": "dimension",
   "css": "--font-size-base",
   "values": {
    "Desktop": 16,
    "iPad": 14,
    "Mobile": 14
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/lg",
   "collection": "Typography",
   "name": "font-size/lg",
   "type": "dimension",
   "css": "--font-size-lg",
   "values": {
    "Desktop": 18,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/sm",
   "collection": "Typography",
   "name": "font-size/sm",
   "type": "dimension",
   "css": "--font-size-sm",
   "values": {
    "Desktop": 14,
    "iPad": 12,
    "Mobile": 12
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/xl",
   "collection": "Typography",
   "name": "font-size/xl",
   "type": "dimension",
   "css": "--font-size-xl",
   "values": {
    "Desktop": 20,
    "iPad": 18,
    "Mobile": 18
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::font-size/xs",
   "collection": "Typography",
   "name": "font-size/xs",
   "type": "dimension",
   "css": "--font-size-xs",
   "values": {
    "Desktop": 12,
    "iPad": 12,
    "Mobile": 12
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/2xl",
   "collection": "Typography",
   "name": "letter-spacing/2xl",
   "type": "dimension",
   "css": "--letter-spacing-2xl",
   "values": {
    "Desktop": -0.4000000059604645,
    "iPad": -0.4000000059604645,
    "Mobile": -0.4000000059604645
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/3xl",
   "collection": "Typography",
   "name": "letter-spacing/3xl",
   "type": "dimension",
   "css": "--letter-spacing-3xl",
   "values": {
    "Desktop": -0.6000000238418579,
    "iPad": -0.6000000238418579,
    "Mobile": -0.6000000238418579
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/4xl",
   "collection": "Typography",
   "name": "letter-spacing/4xl",
   "type": "dimension",
   "css": "--letter-spacing-4xl",
   "values": {
    "Desktop": -0.800000011920929,
    "iPad": -0.800000011920929,
    "Mobile": -0.800000011920929
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/5xl",
   "collection": "Typography",
   "name": "letter-spacing/5xl",
   "type": "dimension",
   "css": "--letter-spacing-5xl",
   "values": {
    "Desktop": -1,
    "iPad": -1,
    "Mobile": -1
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/6xl",
   "collection": "Typography",
   "name": "letter-spacing/6xl",
   "type": "dimension",
   "css": "--letter-spacing-6xl",
   "values": {
    "Desktop": -1.2000000476837158,
    "iPad": -1.2000000476837158,
    "Mobile": -1.2000000476837158
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/base",
   "collection": "Typography",
   "name": "letter-spacing/base",
   "type": "dimension",
   "css": "--letter-spacing-base",
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/lg",
   "collection": "Typography",
   "name": "letter-spacing/lg",
   "type": "dimension",
   "css": "--letter-spacing-lg",
   "values": {
    "Desktop": -0.20000000298023224,
    "iPad": -0.20000000298023224,
    "Mobile": -0.20000000298023224
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/normal",
   "collection": "Typography",
   "name": "letter-spacing/normal",
   "type": "dimension",
   "css": "--letter-spacing-normal",
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/sm",
   "collection": "Typography",
   "name": "letter-spacing/sm",
   "type": "dimension",
   "css": "--letter-spacing-sm",
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/tight",
   "collection": "Typography",
   "name": "letter-spacing/tight",
   "type": "dimension",
   "css": "--letter-spacing-tight",
   "values": {
    "Desktop": -0.4000000059604645,
    "iPad": -0.4000000059604645,
    "Mobile": -0.4000000059604645
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/tighter",
   "collection": "Typography",
   "name": "letter-spacing/tighter",
   "type": "dimension",
   "css": "--letter-spacing-tighter",
   "values": {
    "Desktop": -0.800000011920929,
    "iPad": -0.800000011920929,
    "Mobile": -0.800000011920929
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/wide",
   "collection": "Typography",
   "name": "letter-spacing/wide",
   "type": "dimension",
   "css": "--letter-spacing-wide",
   "values": {
    "Desktop": 0.4000000059604645,
    "iPad": 0.4000000059604645,
    "Mobile": 0.4000000059604645
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/wider",
   "collection": "Typography",
   "name": "letter-spacing/wider",
   "type": "dimension",
   "css": "--letter-spacing-wider",
   "values": {
    "Desktop": 0.800000011920929,
    "iPad": 0.800000011920929,
    "Mobile": 0.800000011920929
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/widest",
   "collection": "Typography",
   "name": "letter-spacing/widest",
   "type": "dimension",
   "css": "--letter-spacing-widest",
   "values": {
    "Desktop": 1.600000023841858,
    "iPad": 1.600000023841858,
    "Mobile": 1.600000023841858
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/xl",
   "collection": "Typography",
   "name": "letter-spacing/xl",
   "type": "dimension",
   "css": "--letter-spacing-xl",
   "values": {
    "Desktop": -0.20000000298023224,
    "iPad": -0.20000000298023224,
    "Mobile": -0.20000000298023224
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::letter-spacing/xs",
   "collection": "Typography",
   "name": "letter-spacing/xs",
   "type": "dimension",
   "css": "--letter-spacing-xs",
   "values": {
    "Desktop": 0.20000000298023224,
    "iPad": 0.20000000298023224,
    "Mobile": 0.20000000298023224
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/2xl",
   "collection": "Typography",
   "name": "line-height/2xl",
   "type": "dimension",
   "css": "--line-height-2xl",
   "values": {
    "Desktop": 32,
    "iPad": 30,
    "Mobile": 28
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/3xl",
   "collection": "Typography",
   "name": "line-height/3xl",
   "type": "dimension",
   "css": "--line-height-3xl",
   "values": {
    "Desktop": 36,
    "iPad": 34,
    "Mobile": 32
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/4xl",
   "collection": "Typography",
   "name": "line-height/4xl",
   "type": "dimension",
   "css": "--line-height-4xl",
   "values": {
    "Desktop": 40,
    "iPad": 38,
    "Mobile": 36
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/5xl",
   "collection": "Typography",
   "name": "line-height/5xl",
   "type": "dimension",
   "css": "--line-height-5xl",
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 40
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/6xl",
   "collection": "Typography",
   "name": "line-height/6xl",
   "type": "dimension",
   "css": "--line-height-6xl",
   "values": {
    "Desktop": 60,
    "iPad": 56,
    "Mobile": 48
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/base",
   "collection": "Typography",
   "name": "line-height/base",
   "type": "dimension",
   "css": "--line-height-base",
   "values": {
    "Desktop": 24,
    "iPad": 22,
    "Mobile": 20
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/lg",
   "collection": "Typography",
   "name": "line-height/lg",
   "type": "dimension",
   "css": "--line-height-lg",
   "values": {
    "Desktop": 28,
    "iPad": 26,
    "Mobile": 24
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/sm",
   "collection": "Typography",
   "name": "line-height/sm",
   "type": "dimension",
   "css": "--line-height-sm",
   "values": {
    "Desktop": 20,
    "iPad": 18,
    "Mobile": 18
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/xl",
   "collection": "Typography",
   "name": "line-height/xl",
   "type": "dimension",
   "css": "--line-height-xl",
   "values": {
    "Desktop": 28,
    "iPad": 26,
    "Mobile": 26
   },
   "resolved": {},
   "description": ""
  },
  {
   "figma": "Typography::line-height/xs",
   "collection": "Typography",
   "name": "line-height/xs",
   "type": "dimension",
   "css": "--line-height-xs",
   "values": {
    "Desktop": 16,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": ""
  }
 ]
} as const;
export default tokens;
