"""Generate the documentation pages of a design system Storybook from its data files.

Usage:  python tools/storybook_docs.py <DS folder> [--replace]
Reads   <folder>/data/component-registry.json, data/tokens.json, data/rules.json,
        data/source/components-live.json (optional: full Figma descriptions and defaults),
        Component_Skills/*/references/components.md (Use / Do not use / Sizes / Content / Accessibility lines),
        <folder>/storybook/component-map.json, storybook/figma-links.json (optional),
        <folder>/storybook/welcome.json (optional: name, summary, product, audience, version, stack, samples),
        Project_Brief.md ("## Product" section, optional), CHANGELOG.md (last date).
Writes  <storybook>/src/docs/DocBlocks.tsx + docs.css  (copied from Storybook_Design_System_Skill/templates/docs/)
        <storybook>/src/docs/Welcome.mdx                (first page: DS summary, product, stats, start here, live samples)
        <storybook>/src/foundations/{Colors,Typography,Sizing,Effects,Icons}.mdx  (tokens shown visually, live)
        <storybook>/src/stories/<Group>/<Component>.mdx (one docs page per Figma component, attached to its stories)

Component pages follow one structure for every design system: Overview + use cases, When to use / not use,
Anatomy, Variants, Sizes, States, Icons, Do and don't, Content, Accessibility, Properties, Playground, From Figma.
Content comes from the registry entry's optional "docs" block first (see the skill, section 3b), then from the Figma
description (Purpose / Usage rules / Accessibility), components.md and rules.json. Names stay the Figma names.

--replace  also overwrites hand-written foundation pages and removes the old Introduction, Spacing, Radius and
           Shadows pages (their content moves to Welcome, Sizing and Effects). Without it, a hand-written page with
           the same name is kept and reported.
"""
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "Storybook_Design_System_Skill" / "templates" / "docs"
GENERATED = "{/* Generated by tools/storybook_docs.py. Do not edit by hand; change the data files and rerun. */}"
TIER_ORDER = ["Atom", "Molecule", "Organism", "Pattern"]
OVERLAY = re.compile(r"modal|dialog|toast|tooltip|drawer|sheet|popover|snackbar|menu|overlay|shell|sidebar|top bar", re.I)
LEGACY_PAGES = ["Introduction.mdx", "Spacing.mdx", "Radius.mdx", "Shadows.mdx"]
STATE_MEANING = {
    "default": "Resting state.",
    "hover": "Pointer over the component.",
    "pressed": "While it is being pressed.",
    "active": "While it is being pressed or is the current item.",
    "focus": "Keyboard focus; shows the focus ring.",
    "focused": "Keyboard focus; shows the focus ring.",
    "disabled": "Not available; it cannot be used.",
    "loading": "The action is running; the label stays.",
    "error": "The value is invalid; shows the error message.",
    "filled": "Has a value.",
    "selected": "Chosen or current item.",
    "read only": "Shows a value that cannot be changed.",
}


def js(value):
    return json.dumps(value, ensure_ascii=False)


def sb_id(*parts):
    """Storybook id of a title: each segment lowercased, runs of other characters become '-'."""
    segs = [re.sub(r"[^a-z0-9]+", "-", p.lower()).strip("-") for p in "/".join(parts).split("/")]
    return "-".join(s for s in segs if s)


def split_items(text):
    return [s.strip().rstrip(".") for s in re.split(r";\s*|\.\s+(?=[A-Z])", text or "") if s.strip()]


def read_json(path, default=None):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else default


def read_component_md(folder):
    """'- Use:' / '- Do not use:' / '- Sizes:' / '- Content:' / '- Accessibility:' lines per '## <Component>'."""
    keys = {"- Use:": "use", "- Do not use:": "dont", "- Sizes:": "sizes", "- Content:": "content", "- Accessibility:": "a11y"}
    out = {}
    for f in (folder / "Component_Skills").glob("*/references/components.md"):
        current = None
        for line in f.read_text(encoding="utf-8").splitlines():
            if line.startswith("## "):
                current = line[3:].strip()
                out.setdefault(current, {})
                continue
            for prefix, key in keys.items():
                if current and line.startswith(prefix):
                    out[current][key] = line[len(prefix):].strip()
    return out


def parse_description(desc):
    """Split a Figma description into Purpose / Usage rules / Accessibility (the house format)."""
    parts = {}
    for label, key in (("Purpose", "purpose"), ("Usage rules", "usage"), ("Accessibility", "a11y")):
        m = re.search(label + r"\s*:\s*(.+?)(?=\n?\s*(Purpose|Usage rules|Accessibility)\s*:|\Z)", desc or "", re.S)
        if m:
            parts[key] = " ".join(m.group(1).split())
    return parts


def strip_md(text):
    return re.sub(r"\*\*(.+?)\*\*", r"\1", text or "").replace("`", "")


# ---------------------------------------------------------------- component pages
def component_docs(c, live, usage, rules, url, rtl=False):
    name = c["name"]
    variants = c.get("variants", {})
    props = c.get("properties", {})
    desc = live.get("description", "")
    d = parse_description(desc)
    u = usage.get(name, {})
    over = c.get("docs", {}) or {}

    rules_text = d.get("usage", "")
    sentences = split_items(rules_text)
    negative = re.compile(r"^(do not|don't|never|avoid)\b", re.I)
    when = [s for s in sentences if not negative.search(s)]
    when_not = [s for s in sentences if negative.search(s)]
    when_not += [strip_md(s) for s in split_items(u.get("dont", ""))]

    use_cases = [strip_md(s) for s in split_items(u.get("use", ""))]

    # main variant axis: the first multi-value variant property that is not State or Size
    axes = [k for k, v in variants.items() if len(v) > 1 and k not in ("State", "Size")]
    main = axes[0] if axes else None
    clauses = split_items(rules_text) + split_items(c.get("use", ""))
    def meaning(value):
        for cl in clauses:
            if re.search(r"(?<![A-Za-z])" + re.escape(value) + r"(?![A-Za-z])", cl):
                return cl
        return None
    variant_items = [{"value": v, "meaning": meaning(v)} for v in variants.get(main, [])] if main else []

    size_text = " ".join([u.get("sizes", ""), c.get("use", "")])
    def size_meaning(v):
        m = re.search(r"(?<![A-Za-z0-9])" + re.escape(v) + r"\s+(\d+)", size_text)
        return f"{m.group(1)}px" if m else None
    sizes = [{"value": v, "meaning": size_meaning(v)} for v in variants.get("Size", [])]
    states = [{"value": v, "meaning": STATE_MEANING.get(v.lower())} for v in variants.get("State", [])]

    slots = [s for s in c.get("slots", []) if s.get("kind") == "instance_swap"]
    if not slots:
        slots = [{"property": k, "accepts": "Icon/*", "default": (c.get("defaults") or {}).get(k)} for k, t in props.items() if t == "INSTANCE_SWAP"]
    def show_prop(slot):
        return next((b for b, t in props.items() if t == "BOOLEAN" and slot.lower() in b.lower()), None)
    icons = [{"property": s["property"], "accepts": s.get("accepts"), "default": s.get("default"), "rule": s.get("rule"),
              "show": show_prop(s["property"])} for s in slots]

    def order(k):
        return 0 if k.lower().startswith("leading") else 2 if k.lower().startswith("trailing") else 1
    anatomy = [{"part": "Container", "detail": "Auto Layout frame; fill, border, radius and padding from tokens."}]
    for k in sorted([k for k, t in props.items() if t in ("TEXT", "INSTANCE_SWAP")], key=order):
        if props[k] == "TEXT":
            anatomy.append({"part": k, "detail": "Text property; uses a text style."})
        else:
            shown = next((b for b, t in props.items() if t == "BOOLEAN" and k.lower() in b.lower()), None)
            anatomy.append({"part": k, "detail": "Icon slot (instance swap)" + (f", shown when {shown} is on" if shown else "") + "."})
    for n in c.get("nests", []):
        if not n.startswith("Icon"):
            anatomy.append({"part": n, "detail": "Nested component instance."})

    guidelines = [{"do": a, "dont": b} for a, b in zip(when, when_not)]
    a11y = split_items(d.get("a11y", ""))
    if u.get("a11y") and not u["a11y"].lower().startswith("see description"):
        a11y += [strip_md(s) for s in split_items(u["a11y"])]
    acc = (rules or {}).get("accessibility", {})
    if acc.get("touch_target_min") and any(t in ("Atom", "Molecule") for t in [c.get("tier")]):
        tt = acc["touch_target_min"]
        a11y.append(f"Touch target at least {tt.get('hard_min')}px, {tt.get('recommended')}px recommended")
    if acc.get("contrast_min", {}).get("text"):
        a11y.append(f"Text contrast at least {acc['contrast_min']['text']}:1 ({acc['contrast_min'].get('ui_boundary', 3)}:1 for borders and icons)")

    docs = {
        "name": name, "group": c.get("group", ""), "tier": c.get("tier", ""), "page": c.get("page", ""),
        "figma_url": url, "variant_count": c.get("variant_count"),
        "overview": d.get("purpose") or c.get("use", ""),
        "use_cases": use_cases, "when_to_use": when, "when_not_to_use": when_not,
        "anatomy": anatomy, "main_axis": main, "variants": variant_items, "sizes": sizes, "states": states,
        "icons": icons, "guidelines": guidelines,
        "content": [strip_md(s) for s in split_items(u.get("content", ""))],
        "accessibility": a11y,
        "built_from": [n for n in c.get("nests", [])],
        "gaps": c.get("issues", []),
        "rtl": rtl,
        "figma_description": desc,
    }
    cap = lambda t: t[:1].upper() + t[1:] if isinstance(t, str) else t
    for k in ("overview",):
        docs[k] = cap(docs[k])
    for k in ("use_cases", "when_to_use", "when_not_to_use", "content", "accessibility"):
        docs[k] = [cap(x) for x in docs[k]]
    docs["guidelines"] = [{"do": cap(g["do"]), "dont": cap(g["dont"])} for g in docs["guidelines"]]
    docs.update({k: v for k, v in over.items() if v is not None})
    return {k: v for k, v in docs.items() if v not in (None, "", [])} | {"name": name, "group": docs["group"], "tier": docs["tier"]}


def is_rtl(folder):
    """Project_Brief.md intake row 'Arabic / RTL' answered Yes (or welcome.json "rtl": true)."""
    extra = read_json(folder / "storybook" / "welcome.json", {})
    if "rtl" in extra:
        return bool(extra["rtl"])
    p = folder / "Project_Brief.md"
    if not p.exists():
        return False
    m = re.search(r"\|\s*(Arabic\s*/\s*RTL|RTL)[^|]*\|\s*([^|]+)\|", p.read_text(encoding="utf-8"), re.I)
    return bool(m and m.group(2).strip().lower().startswith("yes"))


def write_component_docs(folder):
    sb = folder / "storybook"
    registry = read_json(folder / "data" / "component-registry.json")
    cmap = read_json(sb / "component-map.json", {})
    links = read_json(sb / "figma-links.json", {})
    rules = read_json(folder / "data" / "rules.json", {})
    live = {c["name"]: c for c in read_json(folder / "data" / "source" / "components-live.json", {}).get("components", [])}
    usage = read_component_md(folder)
    rtl = is_rtl(folder)
    written = []
    for c in registry["components"]:
        name = c["name"]
        if name not in cmap:
            continue
        node = links.get("components", {}).get(name)
        url = f"{links['file']}?node-id={node.replace(':', '-')}" if node and links.get("file") else registry["meta"].get("figma_url", "")
        docs = component_docs(c, live.get(name, {}), usage, rules, url, rtl)
        safe = re.sub(r"[^0-9A-Za-z]+", "-", name).strip("-")
        gdir = sb / "src" / "stories" / re.sub(r"[^0-9A-Za-z]+", "-", c["group"]).strip("-")
        if not (gdir / f"{safe}.stories.tsx").exists():
            continue
        mdx = "\n".join([
            "import { Meta } from '@storybook/addon-docs/blocks';",
            f"import * as Stories from './{safe}.stories';",
            "import { ComponentDocs } from '../../docs/DocBlocks';",
            "",
            GENERATED,
            "",
            f"export const docs = {json.dumps(docs, ensure_ascii=False, indent=1)};",
            "",
            "<Meta of={Stories} />",
            "",
            "<ComponentDocs docs={docs} stories={Stories} />",
            "",
        ])
        path = gdir / f"{safe}.mdx"
        path.write_text(mdx, encoding="utf-8")
        written.append(path)
    return written


# ---------------------------------------------------------------- welcome + foundations
def count_rules(rules):
    """One rule per entry of each rules.json section (keys of a dict, items of a list); data tables are left out."""
    skip = {"meta", "$comment", "note", "contrast_pairs", "known_fixes"}
    return sum(len(v) if isinstance(v, (dict, list)) else 1 for k, v in (rules or {}).items() if k not in skip)


def brief_section(folder, title):
    p = folder / "Project_Brief.md"
    if not p.exists():
        return None
    m = re.search(r"^## " + re.escape(title) + r"\s*\n(.+?)(?=^## |\Z)", p.read_text(encoding="utf-8"), re.S | re.M)
    return " ".join(m.group(1).split()) if m else None


def welcome_data(folder, registry, tokens, rules, cmap, extra):
    meta = registry.get("meta", {})
    project = meta.get("project") or extra.get("project") or meta.get("figma_file", folder.name)
    platform = meta.get("platform", "")
    comps = [c for c in registry["components"]]
    tiers = {t: [c for c in comps if c.get("tier") == t] for t in TIER_ORDER}
    groups = []
    for c in comps:
        if c["group"] not in [g["name"] for g in groups]:
            groups.append({"name": c["group"], "count": 0, "components": []})
        g = next(g for g in groups if g["name"] == c["group"])
        g["count"] += 1
        g["components"].append(c["name"])

    variables = tokens.get("variables", {})
    roles = {k: (v.get("role") or k).lower() for k, v in tokens.get("collections", {}).items()}
    prim = sum(1 for v in variables.values() if "primitive" in roles.get(v["collection"], ""))
    sem = sum(1 for v in variables.values() if "semantic" in roles.get(v["collection"], ""))
    modes = tokens.get("collections", {}).get(next((k for k, r in roles.items() if "semantic" in r), ""), {}).get("modes", [])
    ts = registry.get("text_styles", {})
    ts_count = ts.get("count") if isinstance(ts, dict) else len(ts)
    icons = registry.get("icons", {})
    icon_count = len(icons.get("names", [])) if isinstance(icons, dict) else len(icons)
    variants_total = meta.get("counts", {}).get("variants_total") or sum(c.get("variant_count") or 0 for c in comps)

    updated = None
    ch = folder / "CHANGELOG.md"
    if ch.exists():
        dates = re.findall(r"^##+ .*?(\d{4}-\d{2}-\d{2})", ch.read_text(encoding="utf-8"), re.M)
        updated = max(dates) if dates else None
    updated = updated or meta.get("source", {}).get("extracted_at")

    start = [{"title": "Foundations", "text": "Colors, typography, sizing, effects and icons, shown from the live tokens.", "id": "foundations-colors--docs"}]
    for t in TIER_ORDER:
        if tiers[t] and tiers[t][0]["name"] in cmap:
            first = tiers[t][0]
            start.append({"title": t + "s", "text": f"{len(tiers[t])} components, e.g. " + ", ".join(c["name"] for c in tiers[t][:4]) + ".",
                          "id": sb_id(first["group"], first["name"]) + "--docs"})

    font = ts.get("font") if isinstance(ts, dict) else None
    pills = [p for p in [platform, font, (" + ".join(modes) if len(modes) > 1 else (f"{modes[0]} only" if modes else None)), "React + Storybook (docs only)"] if p]
    pills += extra.get("stack", [])
    data = {
        "name": extra.get("name") or (project if "design system" in project.lower() else f"{project} {platform} Design System".replace("  ", " ").strip()),
        "summary": extra.get("summary") or f"Tokens, components and usage rules of the {project} design system, synced from Figma so designers, developers and AI agents use the same names.",
        "product": extra.get("product") or brief_section(folder, "Product"),
        "audience": extra.get("audience"),
        "version": extra.get("version"),
        "updated": updated,
        "pills": pills,
        "figma_url": meta.get("figma_url"),
        "stats": [
            {"label": "Tokens", "value": len(variables), "detail": f"{prim} primitives · {sem} semantic · {len(variables) - prim - sem} sizing and type"},
            {"label": "Components", "value": len(comps), "detail": " · ".join(f"{len(v)} {k.lower()}s" for k, v in tiers.items() if v)},
            {"label": "Variants", "value": variants_total, "detail": "every Figma variant has a story"},
            {"label": "Rules", "value": count_rules(rules), "detail": "accessibility, color, spacing and naming" + (f" · {len(rules['contrast_pairs'])} contrast pairs checked" if rules.get("contrast_pairs") else "")},
            {"label": "Text styles", "value": ts_count or 0, "detail": font or ""},
            {"label": "Icons", "value": icon_count, "detail": icons.get("set", "") if isinstance(icons, dict) else ""},
        ],
        "start": start,
        "groups": groups,
        "principles": [
            "Figma is the source of truth. Every component, variant, property and token name here is the Figma name, character for character.",
            "Sidebar groups follow the Figma groups; inside a group, Atoms come before Molecules, Organisms and Patterns.",
            "Each component has a Docs page (use cases, when to use, anatomy, variants, sizes, states, do and don't, accessibility) and stories: Playground, one per variant, States, Sizes and All variants.",
            "Controls are the Figma properties with the Figma defaults. Switch modes from the toolbar.",
            "This is documentation, not production code: copy the names, tokens and behavior into your own codebase.",
        ],
    }
    samples = extra.get("samples") or [c["name"] for t in TIER_ORDER for c in tiers[t] if not OVERLAY.search(c["name"])][:6]
    return data, [s for s in samples if s in cmap]


def write_pages(folder, replace=False):
    sb = folder / "storybook"
    src = sb / "src"
    registry = read_json(folder / "data" / "component-registry.json")
    tokens = read_json(folder / "data" / "tokens.json", {})
    rules = read_json(folder / "data" / "rules.json", {})
    cmap = read_json(sb / "component-map.json", {})
    extra = read_json(sb / "welcome.json", {})
    out, kept = [], []

    (src / "docs").mkdir(parents=True, exist_ok=True)
    for f in TEMPLATES.iterdir():
        shutil.copyfile(f, src / "docs" / f.name)
        out.append(src / "docs" / f.name)

    def write(path, text):
        if path.exists() and not replace and GENERATED not in path.read_text(encoding="utf-8"):
            kept.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        out.append(path)

    # Welcome
    data, samples = welcome_data(folder, registry, tokens, rules, cmap, extra)
    by_name = {c["name"]: c for c in registry["components"]}
    imports, nodes = [], []
    for i, name in enumerate(samples):
        c = by_name[name]
        safe = re.sub(r"[^0-9A-Za-z]+", "-", name).strip("-")
        grp = re.sub(r"[^0-9A-Za-z]+", "-", c["group"]).strip("-")
        if not (src / "stories" / grp / f"{safe}.stories.tsx").exists():
            continue
        imports.append(f"import * as S{i} from '../stories/{grp}/{safe}.stories';")
        nodes.append(f"  {{ name: {js(name)}, id: {js(sb_id(c['group'], name) + '--docs')}, node: <S{i}.default.component {{...S{i}.default.args}} /> }},")
    write(src / "docs" / "Welcome.mdx", "\n".join([
        "import { Meta } from '@storybook/addon-docs/blocks';",
        "import { Welcome } from './DocBlocks';",
        *imports, "", GENERATED, "",
        f"export const welcome = {json.dumps(data, ensure_ascii=False, indent=1)};",
        "", "export const samples = [", *nodes, "];", "",
        '<Meta title="Welcome" />', "", "<Welcome data={welcome} samples={samples} />", "",
    ]))

    # Foundations
    f = src / "foundations"
    head = lambda title, blocks: ["import { Meta } from '@storybook/addon-docs/blocks';", f"import {{ {blocks} }} from '../docs/DocBlocks';", "", GENERATED, "", f'<Meta title="Foundations/{title}" />', ""]
    write(f / "Colors.mdx", "\n".join(head("Colors", "ColorPrimitives, ColorSemantics") + [
        "# Colors", "",
        "Primitives hold the raw values. Semantic variables alias them and are the only colors components use. Every swatch is drawn from its CSS variable, so this page always shows the live tokens; Semantic swatches are shown in every Figma mode.",
        "", "## Semantic", "", "<ColorSemantics />", "", "## Primitives", "", "<ColorPrimitives />", ""]))

    ts = registry.get("text_styles", {}) or {}
    if isinstance(ts, list):
        styles = [s["name"] if isinstance(s, dict) else s for s in ts]
        groups = []
    else:
        styles = ts.get("styles") or [ts.get("naming", "{size}/{weight}").replace("{size}", s).replace("{weight}", w) for s in ts.get("sizes", []) for w in ts.get("weights", [])]
        groups = [{"name": s, "styles": [x for x in styles if x.split("/")[0] == s]} for s in reversed(ts.get("sizes", []))] if ts.get("sizes") else []
    type_modes = next((v.get("modes", []) for k, v in tokens.get("collections", {}).items() if "typography" in (v.get("role") or k).lower()), [])
    type_rules = ["Every text layer uses one text style; never set the size or weight by hand.",
                  "CSS class = Figma style name, lowercased, '/' and spaces become '-' (sm/Semi Bold is .ts-sm-semi-bold).",
                  "Family, size, line height, letter spacing and weight are bound to the Typography variables."]
    if len(type_modes) > 1:
        type_rules.append(f"Sizes change with the {', '.join(type_modes)} modes: switch the mode in the toolbar and the px values below update.")
    scales = []
    if isinstance(ts, dict) and ts.get("sizes") and ts.get("weights"):
        sizes, weights = ts["sizes"], ts["weights"]
        naming = ts.get("naming", "{size}/{weight}")
        style = lambda s, w: naming.replace("{size}", s).replace("{weight}", w)
        cut = sizes.index("xl") if "xl" in sizes else len(sizes) // 2
        heavy = next((w for w in ("Bold", "Semi Bold", "SemiBold") if w in weights), weights[-1])
        light = next((w for w in ("Regular", "Book", "Normal") if w in weights), weights[0])
        scales = [
            {"name": "Headline scale", "note": f"{heavy} weight, for page and section headings.", "styles": [style(s, heavy) for s in sizes[cut:]]},
            {"name": "Body scale", "note": f"{light} weight, for body text, labels and captions.", "styles": [style(s, light) for s in sizes[:cut]]},
        ]
        scales = [s for s in scales if s["styles"]]
    tdata = {"font": (ts.get("font") if isinstance(ts, dict) else None), "styles": styles, "groups": groups, "rules": type_rules, "scales": scales}
    write(f / "Typography.mdx", "\n".join(head("Typography", "TypeSpecimen") + [
        "# Typography", "", "Each style is rendered at its real size. The size and line height on the right are measured from the rendered text.", "",
        f"export const type = {json.dumps(tdata, ensure_ascii=False, indent=1)};", "", "<TypeSpecimen data={type} />", ""]))

    write(f / "Sizing.mdx", "\n".join(head("Sizing", "Sizing") + [
        "# Sizing", "", "Spacing, radius and the other dimension variables, with their value in every Figma mode.", "", "<Sizing />", ""]))

    es = registry.get("effect_styles", []) or []
    es = [e["name"] if isinstance(e, dict) else e for e in es]
    write(f / "Effects.mdx", "\n".join(head("Effects", "Effects") + [
        "# Effects", "", "Figma effect styles (shadows, focus rings) and opacity variables.", "",
        f"export const effects = {js(es)};", "", "<Effects styles={effects} />", ""]))

    icons = registry.get("icons", {})
    note = (f"{icons.get('set', '')} icons, named {icons.get('naming', '')}, {icons.get('size', '')}px. "
            f"{icons.get('color', '')}").strip() if isinstance(icons, dict) else ""
    write(f / "Icons.mdx", "\n".join(head("Icons", "IconGallery") + [
        "# Icons", "", "Icons are instances of the Icon component; components expose them as instance swap properties.", "",
        f"<IconGallery note={{{js(note)}}} />", ""]))

    removed = []
    if replace:
        for name in LEGACY_PAGES:
            p = f / name
            if p.exists():
                p.unlink()
                removed.append(p)
    return out, kept, removed


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        print(__doc__)
        return 1
    folder = ROOT / args[0]
    out, kept, removed = write_pages(folder, replace="--replace" in sys.argv)
    comps = write_component_docs(folder)
    rel = lambda p: p.relative_to(ROOT).as_posix()
    print(f"{len(out)} docs files and {len(comps)} component docs pages written")
    for p in kept:
        print(f"kept hand-written page (rerun with --replace to regenerate): {rel(p)}")
    for p in removed:
        print(f"removed legacy page: {rel(p)}")
    leftovers = [n for n in LEGACY_PAGES if (folder / "storybook" / "src" / "foundations" / n).exists()]
    if leftovers:
        print("legacy foundation pages still present (content now in Welcome, Sizing, Effects): " + ", ".join(leftovers))
    print("storySort order: 'Welcome', 'Foundations', ['Colors', 'Typography', 'Sizing', 'Effects', 'Icons'], then the Figma groups")
    return 0


if __name__ == "__main__":
    sys.exit(main())
