"""Generate one Storybook stories file per Figma component from data/component-registry.json.

Usage:  python tools/storybook_stories.py Trianglz
Reads   <folder>/data/component-registry.json   (names, groups, tiers, variants, properties, use, nests, issues)
        <folder>/storybook/component-map.json   (Figma name -> React export)
        <folder>/storybook/figma-links.json     (Figma file + node ids, optional)
Writes  <folder>/storybook/src/stories/<Group>/<name>.stories.tsx

Every story file uses the Figma names exactly: title "<Group>/<Component name>", argTypes keyed by
the Figma variant and property names, options equal to the Figma variant values. Docs text comes from
the registry (tier, use, nests, known Figma gaps) plus a link back to the Figma component.
The React components themselves are written by hand in src/components/ (visual replicas on tokens).
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TIER_ORDER = {"Atom": 1, "Molecule": 2, "Organism": 3, "Pattern": 4}


def ident(text):
    s = re.sub(r"[^0-9A-Za-z]+", " ", text).title().replace(" ", "")
    return s if s and not s[0].isdigit() else "V" + s


def js(value):
    return json.dumps(value, ensure_ascii=False)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    folder = ROOT / sys.argv[1]
    sb = folder / "storybook"
    registry = json.loads((folder / "data" / "component-registry.json").read_text(encoding="utf-8"))
    cmap = json.loads((sb / "component-map.json").read_text(encoding="utf-8"))
    links = {}
    if (sb / "figma-links.json").exists():
        links = json.loads((sb / "figma-links.json").read_text(encoding="utf-8"))
    out_root = sb / "src" / "stories"
    written, missing = [], []

    for c in registry["components"]:
        name = c["name"]
        m = cmap.get(name)
        if not m:
            missing.append(name)
            continue
        group = c["group"]
        variants = c.get("variants", {})
        props = c.get("properties", {})
        exp = m["export"]
        node = links.get("components", {}).get(name)
        url = f"{links['file']}?node-id={node.replace(':', '-')}" if node and links.get("file") else registry["meta"].get("figma_url", "")

        arg_types, args = {}, {}
        for key, values in variants.items():
            arg_types[key] = {"control": "select" if len(values) > 4 else "inline-radio", "options": values,
                              "description": f"Figma variant property `{key}`", "table": {"category": "Figma variants"}}
            args[key] = "Default" if "Default" in values else values[0]
        uses_icons = False
        for key, kind in props.items():
            if kind == "BOOLEAN":
                arg_types[key] = {"control": "boolean", "description": "Figma boolean property", "table": {"category": "Figma properties"}}
            elif kind == "TEXT":
                arg_types[key] = {"control": "text", "description": "Figma text property", "table": {"category": "Figma properties"}}
            elif kind == "INSTANCE_SWAP":
                uses_icons = True
                arg_types[key] = {"control": "select", "options": "__ICONS__", "description": "Figma instance swap (Icon component)", "table": {"category": "Figma properties"}}

        doc = [f"**Figma:** `{name}` on page `{c.get('page', '')}` ({group}). [Open in Figma]({url})", "",
               f"**Tier:** {c.get('tier', '')}", "", f"**Use:** {c.get('use', '')}"]
        if c.get("nests"):
            doc += ["", "**Built from:** " + ", ".join(f"`{n}`" for n in c["nests"])]
        if c.get("issues"):
            doc += ["", "**Known Figma gaps (see gaps.md):** " + "; ".join(c["issues"])]
        doc += ["", "Controls use the Figma variant and property names exactly. Switch Light/Dark and Desktop/iPad/Mobile from the toolbar."]

        imports = sorted({exp, *m.get("example_imports", [])})
        at_src = json.dumps(arg_types, ensure_ascii=False, indent=2).replace('"__ICONS__"', "iconNames")
        lines = [
            "// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;",
            "// change the registry or src/components and regenerate.",
            "import type { Meta, StoryObj } from '@storybook/react-vite';",
            "import React from 'react';",
            f"import {{ {', '.join(imports)} }} from '../../components/{m['module']}';",
        ]
        if uses_icons:
            lines.append("import { iconNames } from '../../lib/Icon';")
        tier = TIER_ORDER.get(c.get("tier", ""), 9)
        lines += [
            "",
            f"const meta = {{",
            f"  title: {js(group + '/' + name)},",
            f"  component: {exp},",
            f"  tags: ['autodocs', 'tier-{c.get('tier', '').lower()}'],",
            f"  argTypes: {at_src},",
            f"  args: {json.dumps(args, ensure_ascii=False)},",
            f"  parameters: {{",
            f"    figma: {{ name: {js(name)}, page: {js(c.get('page', ''))}, tier: {js(c.get('tier', ''))}, order: {tier} }},",
            f"    design: {{ type: 'figma', url: {js(url)} }},",
            f"    docs: {{ description: {{ component: {js(chr(10).join(doc))} }} }},",
            f"  }},",
            f"}} satisfies Meta<typeof {exp}>;",
            "export default meta;",
            f"type Story = StoryObj<typeof meta>;",
            "",
            "export const Playground: Story = {};",
        ]

        # one story per value of the first variant property
        if variants:
            # the first variant property with more than one value drives the per-value stories
            first, values = next(((k, v) for k, v in variants.items() if len(v) > 1), next(iter(variants.items())))
            used = {"Playground"}
            for v in values:
                sid = ident(v)
                while sid in used:
                    sid += "_"
                used.add(sid)
                lines.append(f"export const {sid}: Story = {{ name: {js(v)}, args: {{ {js(first)}: {js(v)} }} }};")

            # matrix of every value (two axes when the map asks for it)
            axes = m.get("matrix") or [first]
            a = axes[0]
            if len(axes) > 1:
                b = axes[1]
                lines += [
                    "",
                    "export const AllVariants: Story = {",
                    "  name: 'All variants',",
                    "  render: (args) => (",
                    "    <div className=\"sb-col\">",
                    f"      {{{js(variants[a])}.map((x) => (",
                    "        <div key={x}>",
                    f"          <div className=\"sb-cell-label ts-xs-medium\">{a}={{x}}</div>",
                    f"          <div className=\"sb-row\">{{{js(variants[b])}.map((y) => <{exp} key={{y}} {{...args}} {{...{{ {js(a)}: x, {js(b)}: y }} as any}} />)}}</div>",
                    "        </div>",
                    "      ))}",
                    "    </div>",
                    "  ),",
                    "};",
                ]
            else:
                lines += [
                    "",
                    "export const AllVariants: Story = {",
                    "  name: 'All variants',",
                    "  render: (args) => (",
                    "    <div className=\"sb-row\">",
                    f"      {{{js(variants[a])}.map((x) => (",
                    "        <div key={x}>",
                    f"          <div className=\"sb-cell-label ts-xs-medium\">{a}={{x}}</div>",
                    f"          <{exp} {{...args}} {{...{{ {js(a)}: x }} as any}} />",
                    "        </div>",
                    "      ))}",
                    "    </div>",
                    "  ),",
                    "};",
                ]
        if m.get("example"):
            lines += ["", f"export const InUse: Story = {{ name: 'In use (interactive)', render: () => {m['example']} }};"]

        safe = re.sub(r"[^0-9A-Za-z]+", "-", name).strip("-")
        path = out_root / re.sub(r"[^0-9A-Za-z]+", "-", group).strip("-") / f"{safe}.stories.tsx"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append(path.relative_to(ROOT).as_posix())

    print(f"{len(written)} story files written under {out_root.relative_to(ROOT).as_posix()}")
    for n in missing:
        print(f"no entry in component-map.json for: {n}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
