"""Generate Storybook token files from <folder>/data/tokens.json.

Usage:  python tools/tokens_to_css.py Trianglz [--out Trianglz/storybook/src/tokens]
Output: tokens.css  one CSS variable per Figma variable. The first mode of each collection is
                    the :root default; every other mode is a selector
                    [data-<collection>="<Figma mode name>"] set by the Storybook toolbar.
                    Aliases stay aliases (var(--gray-900)).
        tokens.ts   Figma name -> CSS variable, per-mode values, collections and modes, used by the
                    Foundations docs pages and the preview toolbars.

CSS name rule (mechanical, so Figma names stay the source of truth): take the variable name,
lowercase it, turn "/" and spaces into "-", drop anything else that is not a-z 0-9 - _.
Collisions are reported and get the collection as a prefix; nothing is merged silently.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def slug(text):
    s = re.sub(r"[/\s]+", "-", text.strip().lower())
    s = re.sub(r"[^a-z0-9_-]", "", s)
    return re.sub(r"-{2,}", "-", s).strip("-")


def css_value(var, value, names):
    if isinstance(value, dict) and "alias" in value:
        target = names.get(value["alias"])
        return f"var({target})" if target else None
    if var["type"] == "dimension" and isinstance(value, (int, float)):
        return f"{value:g}px"
    if var["type"] == "string":
        family = str(value)
        return f'"{family}"' if " " in family else family
    return str(value)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 1
    folder = ROOT / args[0]
    out = ROOT / args[args.index("--out") + 1] if "--out" in args else folder / "storybook" / "src" / "tokens"
    data = json.loads((folder / "data" / "tokens.json").read_text(encoding="utf-8"))
    variables = data["variables"]
    collections = data["collections"]

    # 1. names, with collision handling
    names, seen, collisions = {}, {}, []
    for key, var in variables.items():
        base = "--" + slug(var["name"])
        if base in seen:
            collisions.append((key, seen[base]))
            base = "--" + slug(var["collection"]) + "-" + slug(var["name"])
        seen[base] = key
        names[key] = base

    # 2. css per collection and mode
    blocks, unresolved = {":root": []}, []
    attrs = {}
    for col, meta in collections.items():
        modes = meta["modes"]
        attrs[col] = "data-" + slug(col)
        for i, mode in enumerate(modes):
            sel = ":root" if i == 0 else f'[{attrs[col]}="{mode}"]'
            blocks.setdefault(sel, [])
    for key, var in variables.items():
        modes = collections[var["collection"]]["modes"]
        for i, mode in enumerate(modes):
            if mode not in var["values"]:
                continue
            value = css_value(var, var["values"][mode], names)
            if value is None:
                unresolved.append(f"{key} ({mode}) -> {var['values'][mode]}")
                resolved = (var.get("resolved") or {}).get(mode)
                if resolved is None:
                    continue
                value = resolved
            sel = ":root" if i == 0 else f'[{attrs[var["collection"]]}="{mode}"]'
            blocks[sel].append(f"  {names[key]}: {value}; /* {key} */")

    lines = [
        "/* Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand. */",
        f"/* Source: {data.get('meta', {}).get('figma_url', '')} */",
    ]
    for sel, decls in blocks.items():
        if decls:
            lines += ["", sel + " {", *decls, "}"]
    out.mkdir(parents=True, exist_ok=True)
    (out / "tokens.css").write_text("\n".join(lines) + "\n", encoding="utf-8")

    ts = {
        "meta": data.get("meta", {}),
        "collections": {c: {"modes": m["modes"], "attribute": attrs[c], "role": m.get("role", "")} for c, m in collections.items()},
        "tokens": [
            {
                "figma": key,
                "collection": v["collection"],
                "name": v["name"],
                "type": v["type"],
                "css": names[key],
                "values": v["values"],
                "resolved": v.get("resolved", {}),
                "description": v.get("description", ""),
            }
            for key, v in variables.items()
        ],
    }
    (out / "tokens.ts").write_text(
        "// Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand.\n"
        "export const tokens = " + json.dumps(ts, ensure_ascii=False, indent=1) + " as const;\n"
        "export default tokens;\n",
        encoding="utf-8",
    )

    print(f"{len(variables)} variables -> {out.relative_to(ROOT).as_posix()}/tokens.css, tokens.ts")
    print(f"mode selectors: {', '.join(s for s in blocks if s != ':root') or 'none'}")
    for key, other in collisions:
        print(f"collision: {key} and {other} share a CSS name; prefixed with the collection")
    for u in unresolved:
        print(f"unresolved alias (used resolved value): {u}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
