"""Generate Storybook token files from <folder>/data/tokens.json.

Usage:  python tools/tokens_to_css.py <DS folder> [--out <DS folder>/storybook/src/tokens]
Output: tokens.css  one CSS variable per Figma variable. The default mode of each collection (Light,
                    Desktop, ... else the first) is the :root value; every mode of a multi-mode
                    collection is also a selector
                    [data-<collection>="<Figma mode name>"] set by the Storybook toolbar.
                    Aliases stay aliases (var(--gray-900)).
        tokens.ts   Figma name -> CSS variable, per-mode values, collections and modes, used by the
                    Foundations docs pages and the preview toolbars.

CSS name rule (mechanical, so Figma names stay the source of truth): take the variable name,
lowercase it, turn "/" and spaces into "-", drop anything else that is not a-z 0-9 - _.
Collisions are reported and get the collection as a prefix; nothing is merged silently.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def slug(text):
    s = re.sub(r"[/\s]+", "-", text.strip().lower())
    s = re.sub(r"[^a-z0-9_-]", "", s)
    return re.sub(r"-{2,}", "-", s).strip("-")


PREFERRED_DEFAULT = ("Light", "Desktop", "Default", "Value", "Mode 1")
FONT_WEIGHTS = {"thin": 100, "extralight": 200, "light": 300, "regular": 400, "medium": 500,
                "semibold": 600, "bold": 700, "extrabold": 800, "black": 900}


def css_value(var, value, names):
    if isinstance(value, dict) and "alias" in value:
        target = names.get(value["alias"])
        return f"var({target})" if target else None
    scopes = var.get("scopes") or []
    if var["type"] == "number" and isinstance(value, (int, float)) and "OPACITY" in scopes:
        # Figma stores opacity as 0-100
        return f"{round(value / 100 if value > 1 else value, 3):g}"
    if var["type"] == "number" and isinstance(value, (int, float)) and "FONT_WEIGHT" in scopes:
        return f"{value:g}"
    if var["type"] in ("dimension", "number") and isinstance(value, (int, float)):
        # Figma FLOAT variables (sizes, spacing, radius, line height, letter spacing) are px
        return f"{round(value, 3):g}px"
    if var["type"] == "string" and re.sub(r"[\s-]", "", str(value)).lower() in FONT_WEIGHTS:
        return str(FONT_WEIGHTS[re.sub(r"[\s-]", "", str(value)).lower()])
    if var["type"] == "string":
        family = str(value)
        return f'"{family}"' if " " in family else family
    return str(value)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 1
    folder = ROOT / args[0]
    out = ROOT / args[args.index("--out") + 1] if "--out" in args else folder / "storybook" / "src" / "tokens"
    data = json.loads((folder / "data" / "tokens.json").read_text(encoding="utf-8"))
    variables = data["variables"]
    collections = data["collections"]

    # 1. names, with collision handling
    names, seen, collisions = {}, {}, []
    for key, var in variables.items():
        base = "--" + slug(var["name"])
        if base in seen:
            collisions.append((key, seen[base]))
            base = "--" + slug(var["collection"]) + "-" + slug(var["name"])
        seen[base] = key
        names[key] = base

    # 2. css per collection and mode
    blocks, unresolved = {":root": []}, []
    attrs, defaults = {}, {}
    for col, meta in collections.items():
        modes = meta["modes"]
        attrs[col] = "data-" + slug(col)
        defaults[col] = next((m for m in PREFERRED_DEFAULT if m in modes), modes[0])
        for mode in modes:
            if len(modes) > 1:
                blocks.setdefault(f'[{attrs[col]}="{mode}"]', [])
    for key, var in variables.items():
        modes = collections[var["collection"]]["modes"]
        for mode in modes:
            if mode not in var["values"]:
                continue
            value = css_value(var, var["values"][mode], names)
            if value is None:
                unresolved.append(f"{key} ({mode}) -> {var['values'][mode]}")
                resolved = (var.get("resolved") or {}).get(mode)
                if resolved is None:
                    continue
                value = resolved
            decl = f"  {names[key]}: {value}; /* {key} */"
            if mode == defaults[var["collection"]]:
                blocks[":root"].append(decl)
            if len(modes) > 1:
                blocks[f'[{attrs[var["collection"]]}="{mode}"]'].append(decl)

    lines = [
        "/* Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand. */",
        f"/* Source: {data.get('meta', {}).get('figma_url', '')} */",
    ]
    for sel, decls in blocks.items():
        if decls:
            lines += ["", sel + " {", *decls, "}"]
    out.mkdir(parents=True, exist_ok=True)
    (out / "tokens.css").write_text("\n".join(lines) + "\n", encoding="utf-8")

    ts = {
        "meta": data.get("meta", {}),
        "collections": {c: {"modes": m["modes"], "default": defaults[c], "attribute": attrs[c], "role": m.get("role", "")} for c, m in collections.items()},
        "tokens": [
            {
                "figma": key,
                "collection": v["collection"],
                "name": v["name"],
                "type": v["type"],
                "css": names[key],
                "values": v["values"],
                "resolved": v.get("resolved", {}),
                "description": v.get("description", ""),
            }
            for key, v in variables.items()
        ],
    }
    (out / "tokens.ts").write_text(
        "// Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand.\n"
        "export const tokens = " + json.dumps(ts, ensure_ascii=False, indent=1) + " as const;\n"
        "export default tokens;\n",
        encoding="utf-8",
    )

    print(f"{len(variables)} variables -> {out.relative_to(ROOT).as_posix()}/tokens.css, tokens.ts")
    print(f"mode selectors: {', '.join(s for s in blocks if s != ':root') or 'none'}")
    for key, other in collisions:
        print(f"collision: {key} and {other} share a CSS name; prefixed with the collection")
    for u in unresolved:
        print(f"unresolved alias (used resolved value): {u}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
