"""Generate Storybook token files from <folder>/data/tokens.json.

Usage:  python tools/tokens_to_css.py <DS folder> [--out <DS folder>/storybook/src/tokens]
Output: tokens.css  one CSS variable per Figma variable. The default mode of each collection (Light,
                    Desktop, ... else the first) is the :root value; every mode of a multi-mode
                    collection is also a selector
                    [data-<collection>="<Figma mode name>"] set by the Storybook toolbar.
                    Aliases stay aliases (var(--gray-900)).
        tokens.ts   Figma name -> CSS variable, per-mode values, collections and modes, used by the
                    Foundations docs pages and the preview toolbars. Each token also carries its platform
                    code names ("code", tools/platform_names.py): SwiftUI on iOS, Jetpack Compose on
                    Android, the CSS variable on Web, so the docs show developers the names they type.
        DesignTokens.swift (iOS) / DesignTokens.kt (Android)  the same tokens as platform source,
                    offered for download on the Foundations/Code page. Mobile Adaptive (iOS + Android in one
                    file, an OS collection with iOS / Android modes): both files, resolved per platform, and
                    every token carries both name lists ("codes") for the Storybook Platform switch.
        ../styles/text-styles.css, effects.css  when the registry's text / effect styles list their bound
                    variables (written only if missing or generated before).

CSS name rule (mechanical, so Figma names stay the source of truth): take the variable name,
lowercase it, turn "/" and spaces into "-", drop anything else that is not a-z 0-9 - _.
Collisions are reported and get the collection as a prefix; nothing is merged silently.
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import platform_names as pn  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent


def slug(text):
    s = re.sub(r"[/\s]+", "-", text.strip().lower())
    s = re.sub(r"[^a-z0-9_-]", "", s)
    return re.sub(r"-{2,}", "-", s).strip("-")


PREFERRED_DEFAULT = ("Light", "Desktop", "Default", "Value", "Mode 1")
FONT_WEIGHTS = {"thin": 100, "extralight": 200, "light": 300, "regular": 400, "medium": 500,
                "semibold": 600, "bold": 700, "extrabold": 800, "black": 900}


def css_value(var, value, names):
    if isinstance(value, dict) and "alias" in value:
        target = names.get(value["alias"])
        return f"var({target})" if target else None
    scopes = var.get("scopes") or []
    if var["type"] == "number" and isinstance(value, (int, float)) and "OPACITY" in scopes:
        # Figma stores opacity as 0-100
        return f"{round(value / 100 if value > 1 else value, 3):g}"
    if var["type"] == "number" and isinstance(value, (int, float)) and "FONT_WEIGHT" in scopes:
        return f"{value:g}"
    if var["type"] in ("dimension", "number") and isinstance(value, (int, float)):
        # Figma FLOAT variables (sizes, spacing, radius, line height, letter spacing) are px
        return f"{round(value, 3):g}px"
    if var["type"] == "boolean" or isinstance(value, bool):
        # Figma BOOLEAN variables (Platform/Is iOS, Direction/Is RTL): 1 / 0, read by the docs and components
        return "1" if value is True or str(value).lower() == "true" else "0"
    if var["type"] == "string" and re.sub(r"[\s-]", "", str(value)).lower() in FONT_WEIGHTS:
        return str(FONT_WEIGHTS[re.sub(r"[\s-]", "", str(value)).lower()])
    if var["type"] == "string":
        family = str(value)
        return f'"{family}"' if " " in family else family
    return str(value)


STYLE_MARK = "/* Generated by tools/tokens_to_css.py from the Figma text and effect styles. Do not edit by hand. */"
FALLBACK_FONTS = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Noto Sans Arabic", sans-serif'


def write_style_css(folder, registry, names):
    """styles/text-styles.css and styles/effects.css from text and effect styles whose fields are bound to variables
    (registry "bound": {"fontSize": "<Collection>::<name>", ...}). Hand-written files without the marker are kept."""
    styles_dir = folder / "storybook" / "src" / "styles"
    written = []

    def write(name, body):
        path = styles_dir / name
        if path.exists() and STYLE_MARK not in path.read_text(encoding="utf-8"):
            return
        styles_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(STYLE_MARK + "\n" + body, encoding="utf-8")
        written.append(path.relative_to(ROOT).as_posix())

    text = [s for s in (registry.get("text_styles") or []) if isinstance(s, dict) and (s.get("bound") or {}).get("fontSize")]
    if text:
        props = {"fontFamily": "font-family", "fontSize": "font-size", "lineHeight": "line-height", "fontWeight": "font-weight", "letterSpacing": "letter-spacing"}
        out = ["/* Class = Figma style name, lowercased, '/' and spaces -> '-' ('Button Label' -> .ts-button-label). */"]
        for s in text:
            out.append(f".ts-{slug(s['name'])} {{ /* {s['name']} */")
            for k, css in props.items():
                key = s["bound"].get(k)
                if key in names:
                    out.append(f"  {css}: var({names[key]}){', ' + FALLBACK_FONTS if k == 'fontFamily' else ''};")
            out.append("}")
        write("text-styles.css", "\n".join(out) + "\n")
    effects = [e for e in (registry.get("effect_styles") or []) if isinstance(e, dict) and e.get("effects")]
    if effects:
        out = [":root, [data-mode-scope] {"]
        for e in effects:
            parts = []
            for fx in e["effects"]:
                if fx.get("type") not in ("DROP_SHADOW", "INNER_SHADOW"):
                    continue
                color = f"var({names[fx['bound']['color']]})" if (fx.get("bound") or {}).get("color") in names else (fx.get("color") or "transparent")
                o = fx.get("offset") or {}
                parts.append(f"{'inset ' if fx['type'] == 'INNER_SHADOW' else ''}{o.get('x', 0):g}px {o.get('y', 0):g}px {fx.get('radius', 0):g}px {fx.get('spread', 0) or 0:g}px {color}")
            if parts:
                out.append(f"  --{slug(e['name'])}: {', '.join(parts)}; /* {e['name']} */")
        out.append("}")
        write("effects.css", "\n".join(out) + "\n")
    return written


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 1
    folder = ROOT / args[0]
    out = ROOT / args[args.index("--out") + 1] if "--out" in args else folder / "storybook" / "src" / "tokens"
    data = json.loads((folder / "data" / "tokens.json").read_text(encoding="utf-8"))
    variables = data["variables"]
    collections = data["collections"]

    # 1. names, with collision handling
    names, seen, collisions = {}, {}, []
    for key, var in variables.items():
        base = "--" + slug(var["name"])
        if base in seen:
            collisions.append((key, seen[base]))
            base = "--" + slug(var["collection"]) + "-" + slug(var["name"])
        seen[base] = key
        names[key] = base

    # 2. css per collection and mode
    # [data-mode-scope] re-declares the aliases of one-mode collections (e.g. Component Specific -> OS) on every
    # element that sets modes, so a panel showing another mode (Android next to iOS) resolves them again there.
    blocks, unresolved = {":root": [], "[data-mode-scope]": []}, []
    attrs, defaults = {}, {}
    for col, meta in collections.items():
        modes = meta["modes"]
        attrs[col] = "data-" + slug(col)
        defaults[col] = meta.get("default") if meta.get("default") in modes else next((m for m in PREFERRED_DEFAULT if m in modes), modes[0])
        for mode in modes:
            if len(modes) > 1:
                blocks.setdefault(f'[{attrs[col]}="{mode}"]', [])
    for key, var in variables.items():
        modes = collections[var["collection"]]["modes"]
        for mode in modes:
            if mode not in var["values"]:
                continue
            value = css_value(var, var["values"][mode], names)
            if value is None:
                unresolved.append(f"{key} ({mode}) -> {var['values'][mode]}")
                resolved = (var.get("resolved") or {}).get(mode)
                if resolved is None:
                    continue
                value = resolved
            decl = f"  {names[key]}: {value}; /* {key} */"
            if mode == defaults[var["collection"]]:
                blocks[":root"].append(decl)
                if len(modes) == 1 and isinstance(var["values"][mode], dict):
                    blocks["[data-mode-scope]"].append(decl)
            if len(modes) > 1:
                blocks[f'[{attrs[var["collection"]]}="{mode}"]'].append(decl)

    lines = [
        "/* Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand. */",
        f"/* Source: {data.get('meta', {}).get('figma_url', '')} */",
    ]
    for sel, decls in blocks.items():
        if decls:
            lines += ["", sel + " {", *decls, "}"]
    out.mkdir(parents=True, exist_ok=True)
    (out / "tokens.css").write_text("\n".join(lines) + "\n", encoding="utf-8")

    registry_path = folder / "data" / "component-registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8")) if registry_path.exists() else {}
    platform = data.get("meta", {}).get("platform") or registry.get("meta", {}).get("platform") or "Web"
    pkey = pn.platform_key(platform)
    roles = {c: m.get("role", "") for c, m in collections.items()}
    for key, v in variables.items():
        v["css"] = names[key]
    codes = pn.assign_codes(variables, platform, roles)
    project = registry.get("meta", {}).get("project") or folder.name
    ts_list = [s for s in (registry.get("text_styles") or []) if isinstance(s, dict)]
    platform_file, platforms = None, []
    if pkey == "ios":
        platform_file = ("DesignTokens.swift", pn.swift_source(variables, collections, ts_list, project))
    elif pkey == "android":
        platform_file = ("DesignTokens.kt", pn.kotlin_source(variables, collections, ts_list, project, roles))
    elif pkey == "adaptive":
        # Mobile Adaptive: one Figma file, OS collection modes iOS / Android -> both files, Storybook Platform switch
        cols_with_default = {c: {**m, "default": defaults[c]} for c, m in collections.items()}
        pmodes = pn.platform_modes(collections)
        for q, source in (("ios", pn.adaptive_swift_source(variables, cols_with_default, ts_list, project)),
                          ("android", pn.adaptive_kotlin_source(variables, cols_with_default, ts_list, project))):
            (out.mkdir(parents=True, exist_ok=True), (out / pn.PLATFORM_FILE[q]).write_text(source, encoding="utf-8"))
            platforms.append({"key": q, "label": pn.PLATFORM_LABEL[q], "mode": pmodes.get(q), "file": pn.PLATFORM_FILE[q]})
    if platform_file:
        (out / platform_file[0]).write_text(platform_file[1], encoding="utf-8")
    styles_written = write_style_css(folder, registry, names)

    ts = {
        "platform": pkey,
        "platform_label": pn.PLATFORM_LABEL[pkey],
        "platform_file": platform_file[0] if platform_file else (platforms[0]["file"] if platforms else "tokens.css"),
        "platforms": platforms,
        "os_collection": pn.os_collection(collections) if pkey == "adaptive" else None,
        "meta": data.get("meta", {}),
        "collections": {c: {"modes": m["modes"], "default": defaults[c], "attribute": attrs[c], "role": m.get("role", "")} for c, m in collections.items()},
        "tokens": [
            {
                "figma": key,
                "collection": v["collection"],
                "name": v["name"],
                "type": v["type"],
                "css": names[key],
                "code": pn.first_codes(codes[key], pkey),
                **({"codes": codes[key]} if pkey == "adaptive" else {}),
                "values": v["values"],
                "resolved": v.get("resolved", {}),
                "description": v.get("description", ""),
            }
            for key, v in variables.items()
        ],
    }
    (out / "tokens.ts").write_text(
        "// Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand.\n"
        "export const tokens = " + json.dumps(ts, ensure_ascii=False, indent=1) + " as const;\n"
        "export default tokens;\n",
        encoding="utf-8",
    )

    files = [platform_file[0]] if platform_file else [p["file"] for p in platforms]
    print(f"{len(variables)} variables -> {out.relative_to(ROOT).as_posix()}/tokens.css, tokens.ts"
          + "".join(f", {f}" for f in files) + f" (platform names: {pn.PLATFORM_LABEL[pkey]})")
    for f in styles_written:
        print(f"generated from the Figma styles: {f}")
    print(f"mode selectors: {', '.join(s for s in blocks if s != ':root') or 'none'}")
    for key, other in collisions:
        print(f"collision: {key} and {other} share a CSS name; prefixed with the collection")
    for u in unresolved:
        print(f"unresolved alias (used resolved value): {u}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
